/* Copyright (c) 2024 Richard Rodger, MIT License */

// The binary escape hatch for the parity corpus.
//
// Corpus content values are JSON strings, so they can only carry bytes that
// survive a UTF-8 round-trip. Binary bodies therefore could not be expressed
// at all — memfs's vol.toJSON() decodes lossily, turning 0xFF into U+FFFD —
// which is why the one binary behaviour that matters (Copy must not corrupt a
// file whose extension is absent from BINARY_EXT) was covered only by
// hand-transcribed per-stack unit tests.
//
// So: wherever a content string appears, the format also accepts
//     {"b64": "<standard base64>"}
//
// WHEN it is emitted is decided by a ROUND-TRIP TEST, not by a judgement
// about UTF-8 validity:
//
//     Buffer.from(buf.toString('utf8'), 'utf8').equals(buf)
//
// That makes the guarantee true by construction — whenever a plain string is
// emitted, Go's []byte(s) reproduces the original bytes exactly — without the
// two stacks having to share a definition of "valid UTF-8". It also rejects
// the encodings a validity check has to reason about separately (overlong
// forms, CESU-8 surrogates, truncated sequences) simply because they do not
// come back.
//
// The corpus is GENERATED by TS and only READ by Go, so TS is the only side
// that ever decides; Go only decodes. There is no second decision site to
// keep in sync, and the existing all-text corpus stays plain strings, so the
// regenerate-and-diff CI gate keeps producing legible diffs.

'use strict'

// enc encodes one content value. Accepts a Buffer or a string.
function enc(value) {
  const buf = Buffer.isBuffer(value) ? value : Buffer.from(String(value), 'utf8')
  const str = buf.toString('utf8')
  if (0 === Buffer.compare(Buffer.from(str, 'utf8'), buf)) {
    return str
  }
  return { b64: buf.toString('base64') }
}


// encMap encodes a path->content map.
function encMap(map) {
  const out = {}
  for (const key of Object.keys(map || {})) {
    out[key] = enc(map[key])
  }
  return out
}


// volOf snapshots the whole volume as encoded content values. The bytes are
// read back through fs because vol.toJSON() has already decoded them to
// (lossy) strings by the time it returns. `nulls` selects what an empty
// directory records: 'keep' preserves toJSON's null, 'empty' records ''.
function volOf(mfs, nulls) {
  const out = {}
  for (const [path, value] of Object.entries(mfs.vol.toJSON())) {
    out[path] = null == value ?
      ('empty' === nulls ? '' : null) :
      enc(mfs.fs.readFileSync(path))
  }
  return out
}


module.exports = { enc, encMap, volOf }
