"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = require("node:test");
const Assert = __importStar(require("node:assert"));
const Fs = __importStar(require("node:fs"));
const Path = __importStar(require("node:path"));
const expect_1 = require("./expect");
const memfs_1 = require("../dist/util/memfs");
const __1 = require("../");
const tree_1 = require("../dist/tree");
// 2025-01-01T00:00:00.000Z
const START_TIME = 1735689600000;
const clock = () => {
    let nowI = 0;
    return () => START_TIME + (++nowI * (60 * 1000));
};
// Generate a component tree given as data, into an in-memory volume.
// `seed` pre-populates that volume, for the components that READ a file.
const gen = async (tree, opts, seed) => {
    const { fs, vol } = (0, memfs_1.memfs)(seed || {});
    const jostraca = (0, __1.Jostraca)({ now: clock() });
    const info = await jostraca.generate({ fs: () => fs, folder: '/top' }, (0, __1.cmpTree)(tree, opts));
    return { info, vol: vol.toJSON() };
};
// THE BRIDGE (src/tree.ts, docs/design/AONTU.0.md). A component tree
// as plain data -- the shape aontu's Folder/File/Content primitives
// evaluate to -- generated by the same components a hand-written
// generator calls.
(0, node_test_1.describe)('tree', () => {
    // The worked example from the design note, verbatim: this is what
    // `aontu model.aon` prints for the aontu document there.
    (0, node_test_1.test)('aontu-tree-generates-files', async () => {
        const { info, vol } = await gen({
            cmp: 'Folder',
            props: { name: 'src' },
            children: [{
                    cmp: 'File',
                    props: { name: 'planet.ts' },
                    children: [
                        {
                            cmp: 'Content',
                            props: { src: 'export interface Planet {\n' },
                            children: [],
                        },
                        { cmp: 'Content', props: { src: '  id: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '  name: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '  mass: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '}\n' }, children: [] },
                    ],
                }],
        });
        (0, expect_1.expect)(info.files.written).equal(['/top/src/planet.ts']);
        Assert.equal(vol['/top/src/planet.ts'], 'export interface Planet {\n' +
            '  id: string\n' +
            '  name: string\n' +
            '  mass: string\n' +
            '}\n');
    });
    // A list root becomes siblings, which is what generate's synthetic
    // root node is for.
    (0, node_test_1.test)('sibling-roots', async () => {
        const { info } = await gen([
            {
                cmp: 'File', props: { name: 'a.txt' },
                children: [{ cmp: 'Content', props: { src: 'A' } }],
            },
            {
                cmp: 'File', props: { name: 'b.txt' },
                children: [{ cmp: 'Content', props: { src: 'B' } }],
            },
        ]);
        (0, expect_1.expect)(info.files.written).equal(['/top/a.txt', '/top/b.txt']);
    });
    // `props` and `children` are optional: a leaf with nothing to say is
    // a legitimate node.
    (0, node_test_1.test)('optional-props-and-children', async () => {
        const { info, vol } = await gen({
            cmp: 'Folder',
            props: { name: 'empty' },
        });
        (0, expect_1.expect)(info.files.written).equal([]);
        // The folder is still made.
        Assert.equal(vol['/top/empty'], null);
    });
    // NOTHING HERE IS LIMITED TO THE THREE PRIMITIVES aontu serves so
    // far: `cmp` names a registered component, so one this file has never
    // heard of works as soon as it has an entry.
    //
    // THE DRIFT GUARD is the second half of that claim, and it reads
    // `src/cmp/` rather than restating a list: a component file with no
    // entry in TREE_CMP is a component a data tree cannot reach, and
    // nothing else would say so. `None` is internal -- `generate` uses it
    // for the synthetic root node and no tree may name it.
    (0, node_test_1.test)('every-exported-component-is-reachable', async () => {
        const cmpdir = Path.join(__dirname, '..', 'src', 'cmp');
        const onDisk = Fs.readdirSync(cmpdir)
            .filter((f) => f.endsWith('.ts'))
            .map((f) => f.replace(/\.ts$/, ''))
            .filter((n) => 'None' !== n)
            .sort();
        Assert.deepEqual(Object.keys(__1.TREE_CMP).sort(), onDisk, 'src/cmp/ and TREE_CMP disagree: a component landed unreachable');
        const { info, vol } = await gen({
            cmp: 'Project',
            props: { folder: 'sdk' },
            children: [{
                    cmp: 'File',
                    props: { name: 'x.txt' },
                    children: [
                        { cmp: 'Content', props: { src: 'a' } },
                        { cmp: 'Line', props: { src: 'b' } },
                    ],
                }],
        });
        (0, expect_1.expect)(info.files.written).equal(['/top/sdk/x.txt']);
        Assert.equal(vol['/top/sdk/x.txt'], 'ab\n');
    });
    // A PROP THE BRIDGE KNOWS NOTHING ABOUT reaches the component, which
    // is what makes the vocabulary need no entry per component. `indent`
    // is the one an aontu generator wants first: a span's own depth is
    // expressible without a new primitive.
    (0, node_test_1.test)('props-reach-the-component', async () => {
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'a.ts' },
            children: [
                { cmp: 'Content', props: { src: 'class X {\n' } },
                { cmp: 'Content', props: { src: 'y = 1\n', indent: 2 } },
                { cmp: 'Content', props: { src: '}\n' } },
            ],
        });
        Assert.equal(vol['/top/a.ts'], 'class X {\n  y = 1\n}\n');
    });
    // THE NAMES TWO COMPONENTS SHIPPED UNDER still resolve, so a tree
    // written against `Copy` or `List` keeps working.
    (0, node_test_1.test)('deprecated-names-still-resolve', async () => {
        Assert.deepEqual(Object.keys(tree_1.TREE_CMP_DEPRECATED).sort(), ['Copy', 'List']);
        Assert.equal(tree_1.TREE_CMP_DEPRECATED.Copy, __1.TREE_CMP.CopyFiles);
        Assert.equal(tree_1.TREE_CMP_DEPRECATED.List, __1.TREE_CMP.ListItems);
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'l.txt' },
            children: [{
                    cmp: 'List',
                    props: { item: [{ n: 1 }, { n: 2 }] },
                    children: [{ cmp: 'Content', props: { src: 'n={item.n}\n' } }],
                }],
        });
        Assert.equal(vol['/top/l.txt'], 'n=1\nn=2\n\n');
    });
    // A caller may add their own component, or override one.
    (0, node_test_1.test)('custom-components', async () => {
        const Twice = (0, __1.cmp)(function Twice(props) {
            const node = props.ctx$.node;
            node.kind = 'content';
            node.content = props.src + props.src;
        });
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'x.txt' },
            children: [{ cmp: 'Twice', props: { src: 'ab' } }],
        }, { cmp: { Twice } });
        Assert.equal(vol['/top/x.txt'], 'abab');
    });
    // THE TREE IS THE CALLER'S DATA and must come back unchanged: `cmp()`
    // writes `ctx$` into the props object it is handed, so the bridge
    // passes a copy. Without it a tree parsed once and generated twice
    // carries the first run's context into the second.
    (0, node_test_1.test)('the-tree-is-not-scribbled-on', async () => {
        const tree = {
            cmp: 'File',
            props: { name: 'x.txt' },
            children: [{ cmp: 'Content', props: { src: 'a' } }],
        };
        const before = JSON.stringify(tree);
        await gen(tree);
        Assert.equal(JSON.stringify(tree), before);
        // ... and generating the same tree again is the same generation.
        const { vol } = await gen(tree);
        Assert.equal(vol['/top/x.txt'], 'a');
    });
    // A MALFORMED TREE IS REFUSED BY THE CALL THAT READS IT, before the
    // define phase has made a folder.
    (0, node_test_1.test)('malformed-trees-are-refused', () => {
        const bad = (tree) => {
            try {
                (0, __1.cmpTree)(tree);
            }
            catch (err) {
                return err.message;
            }
            return undefined;
        };
        Assert.match(bad(null), /node is not an object \(at \[0\]\)/);
        Assert.match(bad('File'), /node is not an object/);
        Assert.match(bad({}), /node has no cmp name/);
        Assert.match(bad({ cmp: '' }), /node has no cmp name/);
        Assert.match(bad({ cmp: 'Nope' }), /unknown component: Nope/);
        Assert.match(bad({ cmp: 'File', props: [] }), /props is not an object/);
        Assert.match(bad({ cmp: 'File', children: {} }), /children is not an array/);
        // The path names the offending node.
        Assert.match(bad({ cmp: 'Folder', children: [{ cmp: 'File', children: [{}] }] }), /node has no cmp name \(at \[0\]\/Folder\[0\]\/File\[0\]\)/);
        // A NAME INHERITED FROM Object.prototype IS NOT A COMPONENT.
        // `cmps['toString']` answers on any ordinary object, and the call
        // then ran `Object.prototype.toString` as a component: no node, no
        // output, and no error to say so.
        Assert.match(bad({ cmp: 'toString' }), /unknown component: toString/);
        Assert.match(bad({ cmp: 'constructor' }), /unknown component: constructor/);
    });
    // THE TREE MAY NOT CHOOSE THE OUTPUT ROOT. `ProjectOp` takes `folder`
    // as given -- an absolute path unchanged, a relative one joined to the
    // base -- which is right when a developer wrote the call and wrong
    // when the tree arrived as JSON: `cmptree-gen --folder ./build` would
    // otherwise write wherever the input said. `File` and `Folder` names
    // are already refused a `..` segment by `validName`; `folder` had no
    // such check because nothing could reach it from data.
    (0, node_test_1.test)('a-tree-cannot-escape-the-output-folder', async () => {
        const bad = (folder) => {
            try {
                (0, __1.cmpTree)({ cmp: 'Project', props: { folder } });
            }
            catch (err) {
                return err.message;
            }
            return undefined;
        };
        Assert.match(bad('/escaped'), /folder must not be absolute/);
        Assert.match(bad('../../escaped'), /folder must not contain a "\.\." segment/);
        Assert.match(bad('a/../../b'), /folder must not contain a "\.\." segment/);
        Assert.match(bad(1), /folder is not a string/);
        // A folder BELOW the root is what the prop is for, and still works.
        const { info } = await gen({
            cmp: 'Project',
            props: { folder: 'sdk' },
            children: [{
                    cmp: 'File', props: { name: 'x.txt' },
                    children: [{ cmp: 'Content', props: { src: 'a' } }],
                }],
        });
        (0, expect_1.expect)(info.files.written).equal(['/top/sdk/x.txt']);
    });
    // THE PARENT'S ARGUMENTS REACH THE CHILD. `List` walks its children
    // once per item with `{item, indent, replace}`, and the `{item.n}`
    // macro means nothing without them -- a hand-written child takes them
    // as its parameter, and a data child has no parameter list, so the
    // thunk merges them under the node's own props.
    (0, node_test_1.test)('list-items-reach-their-children', async () => {
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'l.txt' },
            children: [{
                    cmp: 'ListItems',
                    props: { item: [{ n: 1 }, { n: 2 }] },
                    children: [{ cmp: 'Content', props: { src: 'n={item.n}\n' } }],
                }],
        });
        Assert.equal(vol['/top/l.txt'], 'n=1\nn=2\n\n');
    });
    // THE COPY IS DEEP ENOUGH THAT NO COMPONENT CAN REACH THE TREE. A
    // spread of the outer props was not: `Fragment` writes its slot
    // markers into `props.replace`, so a tree carrying one came back with
    // extra keys, accumulated them on a second generate, and threw
    // outright if the map was frozen.
    (0, node_test_1.test)('nested-props-are-not-scribbled-on', async () => {
        const from = '/frag.txt';
        const seed = { [from]: 'HEADER\n<[SLOT]>\nFOOTER\n' };
        const replace = {};
        const tree = {
            cmp: 'File',
            props: { name: 'f.txt' },
            children: [{
                    cmp: 'Fragment',
                    props: { from, replace },
                    children: [{ cmp: 'Content', props: { src: 'BODY\n' } }],
                }],
        };
        const first = await gen(tree, undefined, seed);
        Assert.equal(first.vol['/top/f.txt'], 'HEADER\nBODY\n\nFOOTER\n');
        // The caller's own map is untouched ...
        Assert.deepEqual(Object.keys(replace), []);
        // ... so a frozen one generates rather than throwing, and the same
        // tree generates the same bytes a second time.
        Object.freeze(replace);
        const second = await gen(tree, undefined, seed);
        Assert.equal(second.vol['/top/f.txt'], 'HEADER\nBODY\n\nFOOTER\n');
    });
});
//# sourceMappingURL=tree.test.js.map