"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
const node_test_1 = require("node:test");
const Assert = __importStar(require("node:assert"));
const expect_1 = require("./expect");
const memfs_1 = require("../dist/util/memfs");
const __1 = require("../");
// 2025-01-01T00:00:00.000Z
const START_TIME = 1735689600000;
const clock = () => {
    let nowI = 0;
    return () => START_TIME + (++nowI * (60 * 1000));
};
// Generate a component tree given as data, into an in-memory volume.
const gen = async (tree, opts) => {
    const { fs, vol } = (0, memfs_1.memfs)({});
    const jostraca = (0, __1.Jostraca)({ now: clock() });
    const info = await jostraca.generate({ fs: () => fs, folder: '/top' }, (0, __1.cmpTree)(tree, opts));
    return { info, vol: vol.toJSON() };
};
// THE BRIDGE (src/tree.ts, docs/design/AONTU.0.md). A component tree
// as plain data -- the shape aontu's Folder/File/Content primitives
// evaluate to -- generated by the same components a hand-written
// generator calls.
(0, node_test_1.describe)('tree', () => {
    // The worked example from the design note, verbatim: this is what
    // `aontu model.aon` prints for the aontu document there.
    (0, node_test_1.test)('aontu-tree-generates-files', async () => {
        const { info, vol } = await gen({
            cmp: 'Folder',
            props: { name: 'src' },
            children: [{
                    cmp: 'File',
                    props: { name: 'planet.ts' },
                    children: [
                        {
                            cmp: 'Content',
                            props: { src: 'export interface Planet {\n' },
                            children: [],
                        },
                        { cmp: 'Content', props: { src: '  id: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '  name: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '  mass: string\n' }, children: [] },
                        { cmp: 'Content', props: { src: '}\n' }, children: [] },
                    ],
                }],
        });
        (0, expect_1.expect)(info.files.written).equal(['/top/src/planet.ts']);
        Assert.equal(vol['/top/src/planet.ts'], 'export interface Planet {\n' +
            '  id: string\n' +
            '  name: string\n' +
            '  mass: string\n' +
            '}\n');
    });
    // A list root becomes siblings, which is what generate's synthetic
    // root node is for.
    (0, node_test_1.test)('sibling-roots', async () => {
        const { info } = await gen([
            {
                cmp: 'File', props: { name: 'a.txt' },
                children: [{ cmp: 'Content', props: { src: 'A' } }],
            },
            {
                cmp: 'File', props: { name: 'b.txt' },
                children: [{ cmp: 'Content', props: { src: 'B' } }],
            },
        ]);
        (0, expect_1.expect)(info.files.written).equal(['/top/a.txt', '/top/b.txt']);
    });
    // `props` and `children` are optional: a leaf with nothing to say is
    // a legitimate node.
    (0, node_test_1.test)('optional-props-and-children', async () => {
        const { info, vol } = await gen({
            cmp: 'Folder',
            props: { name: 'empty' },
        });
        (0, expect_1.expect)(info.files.written).equal([]);
        // The folder is still made.
        Assert.equal(vol['/top/empty'], null);
    });
    // NOTHING HERE IS LIMITED TO THE THREE PRIMITIVES aontu serves so
    // far: `cmp` names an exported component, so one this file has never
    // heard of works the moment it is exported.
    (0, node_test_1.test)('every-exported-component-is-reachable', async () => {
        Assert.deepEqual(Object.keys(__1.TREE_CMP).sort(), [
            'Content', 'Copy', 'File', 'Folder', 'Fragment',
            'Inject', 'Line', 'List', 'Project', 'Slot',
        ]);
        const { info, vol } = await gen({
            cmp: 'Project',
            props: { folder: 'sdk' },
            children: [{
                    cmp: 'File',
                    props: { name: 'x.txt' },
                    children: [
                        { cmp: 'Content', props: { src: 'a' } },
                        { cmp: 'Line', props: { src: 'b' } },
                    ],
                }],
        });
        (0, expect_1.expect)(info.files.written).equal(['/top/sdk/x.txt']);
        Assert.equal(vol['/top/sdk/x.txt'], 'ab\n');
    });
    // A PROP THE BRIDGE KNOWS NOTHING ABOUT reaches the component, which
    // is what makes the vocabulary need no entry per component. `indent`
    // is the one an aontu generator wants first: a span's own depth is
    // expressible without a new primitive.
    (0, node_test_1.test)('props-reach-the-component', async () => {
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'a.ts' },
            children: [
                { cmp: 'Content', props: { src: 'class X {\n' } },
                { cmp: 'Content', props: { src: 'y = 1\n', indent: 2 } },
                { cmp: 'Content', props: { src: '}\n' } },
            ],
        });
        Assert.equal(vol['/top/a.ts'], 'class X {\n  y = 1\n}\n');
    });
    // A caller may add their own component, or override one.
    (0, node_test_1.test)('custom-components', async () => {
        const Twice = (0, __1.cmp)(function Twice(props) {
            const node = props.ctx$.node;
            node.kind = 'content';
            node.content = props.src + props.src;
        });
        const { vol } = await gen({
            cmp: 'File',
            props: { name: 'x.txt' },
            children: [{ cmp: 'Twice', props: { src: 'ab' } }],
        }, { cmp: { Twice } });
        Assert.equal(vol['/top/x.txt'], 'abab');
    });
    // THE TREE IS THE CALLER'S DATA and must come back unchanged: `cmp()`
    // writes `ctx$` into the props object it is handed, so the bridge
    // passes a copy. Without it a tree parsed once and generated twice
    // carries the first run's context into the second.
    (0, node_test_1.test)('the-tree-is-not-scribbled-on', async () => {
        const tree = {
            cmp: 'File',
            props: { name: 'x.txt' },
            children: [{ cmp: 'Content', props: { src: 'a' } }],
        };
        const before = JSON.stringify(tree);
        await gen(tree);
        Assert.equal(JSON.stringify(tree), before);
        // ... and generating the same tree again is the same generation.
        const { vol } = await gen(tree);
        Assert.equal(vol['/top/x.txt'], 'a');
    });
    // A MALFORMED TREE IS REFUSED BY THE CALL THAT READS IT, before the
    // define phase has made a folder.
    (0, node_test_1.test)('malformed-trees-are-refused', () => {
        const bad = (tree) => {
            try {
                (0, __1.cmpTree)(tree);
            }
            catch (err) {
                return err.message;
            }
            return undefined;
        };
        Assert.match(bad(null), /node is not an object \(at \[0\]\)/);
        Assert.match(bad('File'), /node is not an object/);
        Assert.match(bad({}), /node has no cmp name/);
        Assert.match(bad({ cmp: '' }), /node has no cmp name/);
        Assert.match(bad({ cmp: 'Nope' }), /unknown component: Nope/);
        Assert.match(bad({ cmp: 'File', props: [] }), /props is not an object/);
        Assert.match(bad({ cmp: 'File', children: {} }), /children is not an array/);
        // The path names the offending node.
        Assert.match(bad({ cmp: 'Folder', children: [{ cmp: 'File', children: [{}] }] }), /node has no cmp name \(at \[0\]\/Folder\[0\]\/File\[0\]\)/);
    });
});
//# sourceMappingURL=tree.test.js.map