package jostraca

// HOLD A COMMITTED TREE TO WHAT THE GENERATORS PRODUCE (twin of
// ts/src/check.ts).
//
//	res, err := jostraca.New().Check(jostraca.Options{Folder: "app"}, root)
//	if len(res.Drift) > 0 { /* the tree is stale */ }
//
// Generate into memory, compare with the folder, and answer with the
// difference as DATA. It is the CI half of generating: a generator is
// run, its output is committed and reviewed, and the question a build
// asks from then on is whether the two still agree.
//
// A GENERATION MODE, NOT A TOOL. Mem, the existing-file modes and the
// dry run are all options on Generate, and this belongs beside them:
// every generator wants this gate, whether it is written in Go at the
// call site or arrives as a component tree from another language.
//
// The shadow, what it buys and what it costs, are the same on both
// sides and the TypeScript file carries the long form. In brief: the
// folder is invisible to the run, so nothing committed can change what
// the generators produce; every write goes to memory, so a check
// changes nothing; reads outside the folder fall through, so a Fragment
// or CopyFiles source is read as it would be; and Inject, which rewrites
// a file that already exists, is the one component the shadow cannot
// serve.

import (
	"bytes"
	"io/fs"
	"path"
	"sort"
	"strings"
)

// DriftKind says which question a file failed.
type DriftKind string

const (
	// DriftMissing: the generators claim it and the folder does not
	// hold it.
	DriftMissing DriftKind = "missing"

	// DriftContent: the bytes differ.
	DriftContent DriftKind = "content"

	// DriftMode: the bytes match and the permission bits do not, where
	// the tree stated them with FileProps.Mode.
	DriftMode DriftKind = "mode"
)

// Drift is one way a committed file differs from what the generators
// produce. The bytes are carried rather than rendered: a build wants an
// exit code, a test wants an assertion, a reviewer wants hunks.
type Drift struct {
	// Path relative to the checked folder, forward slashes.
	Path string

	Kind DriftKind

	// What the generators produce. Always set -- a missing file still
	// has generated bytes, which is what would be written.
	Generated []byte

	// What the folder holds. Nil when Kind is DriftMissing.
	Existing []byte

	// The mode the tree declared, and the bits on disk. Both set only
	// when Kind is DriftMode.
	Mode         fs.FileMode
	ExistingMode fs.FileMode
}

// CheckResult is what Check answers.
type CheckResult struct {
	// The folder that was checked, as given.
	Folder string

	// Every path compared, relative and sorted. A file the generators
	// do not claim is not here.
	Checked []string

	// Sorted by path. Empty means the folder is what the generators
	// produce.
	Drift []Drift

	// The run report of the generate that produced the comparison.
	Files Files
}

// jostraca's own bookkeeping under the output folder. Timestamped, so
// never byte-stable, and never part of what a generator claims.
const checkMetaFolder = ".jostraca"

// shadowFS is memory under `root`, `base` outside it.
//
// `base` is the filesystem holding the committed tree. Keeping it a
// field rather than reaching for OsFS is what lets a test check one
// in-memory tree against another without touching disk.
//
// `modes` records A MODE THE RUN ACTUALLY ASKED FOR. The volume cannot
// answer that on its own, because it gives every file a default mode,
// so "what is this file's mode in memory" does not distinguish a File
// that stated one from a File that said nothing. The narrower question
// is only visible here, where the file handler passes it.
type shadowFS struct {
	mem   *MemFS
	base  FS
	root  string
	modes map[string]fs.FileMode
}

func newShadowFS(base FS, root string) *shadowFS {
	return &shadowFS{
		mem:   NewMemFS(),
		base:  base,
		root:  root,
		modes: map[string]fs.FileMode{},
	}
}

// under reports whether p is at or below root, on a path BOUNDARY:
// `/out2/a` is not under `/out`, however much of the string it shares.
func (s *shadowFS) under(p string) bool {
	cp := memClean(p)
	return cp == s.root || strings.HasPrefix(cp, s.root+"/")
}

// pick routes a READ: memory inside the folder, base outside it.
func (s *shadowFS) pick(p string) FS {
	if s.under(p) {
		return s.mem
	}
	return s.base
}

func (s *shadowFS) ReadFile(p string) ([]byte, error) { return s.pick(p).ReadFile(p) }
func (s *shadowFS) Exists(p string) bool              { return s.pick(p).Exists(p) }
func (s *shadowFS) Stat(p string) (FileInfo, error)   { return s.pick(p).Stat(p) }
func (s *shadowFS) ReadDir(p string) ([]DirEntry, error) {
	return s.pick(p).ReadDir(p)
}

// EVERY WRITE GOES TO MEMORY, including one aimed outside the folder. A
// command that only asks a question must not be able to answer it by
// changing something.
func (s *shadowFS) WriteFile(p string, data []byte) error {
	return s.mem.WriteFile(p, data)
}

func (s *shadowFS) MkdirAll(p string) error { return s.mem.MkdirAll(p) }
func (s *shadowFS) Remove(p string) error   { return s.mem.Remove(p) }

// The atomic write lands under a temp name and is renamed into place,
// so a declared mode follows the bytes to their final path.
func (s *shadowFS) Rename(oldpath, newpath string) error {
	if mode, held := s.modes[memClean(oldpath)]; held {
		s.modes[memClean(newpath)] = mode
		delete(s.modes, memClean(oldpath))
	}
	return s.mem.Rename(oldpath, newpath)
}

// Chmod is where a declared mode becomes visible, and implementing it
// is the whole reason the shadow is a type rather than a MemFS: the
// file handler feature-detects chmodFS, and MemFS does not implement
// it, so a memory run would never be asked about a mode at all.
//
// RECORDED, NOT APPLIED. There is nothing in the volume to apply it to
// -- MemFS keeps no modes -- and the record is what the comparison
// needs. The handler calls this on the TEMP path with an explicit mode,
// and Rename carries the record to the final path.
//
// A File that states NO mode does not reach here: the handler's other
// arm chmods to the existing target's mode, and under the shadow the
// target does not exist, so nothing is declared. That is what keeps a
// silent File held to nothing.
func (s *shadowFS) Chmod(p string, mode fs.FileMode) error {
	s.modes[memClean(p)] = mode & fs.ModePerm
	return nil
}

// generated walks what the run produced, by path relative to root.
func (s *shadowFS) generated() map[string][]byte {
	out := map[string][]byte{}

	var walk func(dir, rel string)
	walk = func(dir, rel string) {
		entries, err := s.mem.ReadDir(dir)
		if err != nil {
			// Nothing was generated under it, which is not an error: an
			// empty tree is a clean check against an empty claim.
			return
		}
		for _, e := range entries {
			key := e.Name
			if rel != "" {
				key = rel + "/" + e.Name
			}
			if key == checkMetaFolder ||
				strings.HasPrefix(key, checkMetaFolder+"/") {
				continue
			}
			// An EMPTY dir is the root, and joining it with a slash
			// would build "/a.txt" -- a DIFFERENT key here, where the
			// write landed at "a.txt". The TypeScript twin survives
			// the same line because memfs roots a relative path at /,
			// so the two spell one file; MemFS does not.
			full := e.Name
			if dir != "" {
				full = dir + "/" + e.Name
			}
			if e.IsDir {
				walk(full, key)
				continue
			}
			data, err := s.mem.ReadFile(full)
			if err != nil {
				continue
			}
			out[key] = data
		}
	}

	walk(s.root, "")
	return out
}

// Check runs Generate against a shadowed folder and compares.
//
// It takes the same Options as Generate; Folder is the folder checked.
// FS, if set, is the filesystem holding the committed tree.
func (j *J) Check(opts Options, root func(*J)) (CheckResult, error) {
	folder := opts.Folder
	if folder == "" {
		folder = j.st.opts.Folder
	}
	if folder == "" {
		folder = "."
	}

	var base FS = opts.FS
	if base == nil {
		base = j.st.opts.FS
	}
	if base == nil {
		base = OsFS{}
	}

	shadow := newShadowFS(base, memClean(folder))

	run := opts
	run.Folder = folder
	run.FS = shadow

	// Forced, because each would answer a different question than the
	// one asked. NoDuplicate off would write a `.jostraca/generated`
	// baseline for a later merge, and a check makes no next run to
	// merge into; a dry run would write nothing to the volume, leaving
	// nothing to compare.
	run.Control.NoDuplicate = true
	run.Control.Dryrun = false

	res, err := j.Generate(run, root)
	if err != nil {
		return CheckResult{}, err
	}

	files := shadow.generated()

	checked := make([]string, 0, len(files))
	for p := range files {
		checked = append(checked, p)
	}
	sort.Strings(checked)

	out := CheckResult{
		Folder:  folder,
		Checked: checked,
		Files:   res.Files,
	}

	for _, p := range checked {
		gen := files[p]
		at := path.Join(folder, p)

		have, rerr := base.ReadFile(at)
		if rerr != nil {
			out.Drift = append(out.Drift, Drift{
				Path: p, Kind: DriftMissing, Generated: gen,
			})
			continue
		}

		if !bytes.Equal(gen, have) {
			out.Drift = append(out.Drift, Drift{
				Path: p, Kind: DriftContent, Generated: gen, Existing: have,
			})
			continue
		}

		// A MODE IS OUTPUT TOO, where the tree declared one. A file
		// with the right bytes and the wrong bits is drift no byte
		// comparison can see: a run would chmod it and the gate would
		// have said clean. A File that says nothing about mode leaves
		// whatever is there, so there is nothing to hold it to.
		mode, declared := shadow.modes[memClean(path.Join(shadow.root, p))]
		if !declared {
			continue
		}
		info, serr := base.Stat(at)
		if serr != nil {
			continue
		}
		if info.Mode&fs.ModePerm != mode&fs.ModePerm {
			out.Drift = append(out.Drift, Drift{
				Path: p, Kind: DriftMode, Generated: gen, Existing: have,
				Mode: mode & fs.ModePerm, ExistingMode: info.Mode & fs.ModePerm,
			})
		}
	}

	return out, nil
}
