package jostraca

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
)

// THE CHECK GENERATION MODE (check.go, twin of ts/src/check.ts).
//
// MOSTLY IN MEMORY, which is the point: the folder a check runs against
// is read through Options.FS, so a test can hold one in-memory tree
// against another and never touch disk.

// checkMem checks a generator against a committed tree, both in memory.
func checkMem(
	t *testing.T,
	committed map[string][]byte,
	root func(*J),
) CheckResult {
	t.Helper()
	base := NewMemFS()
	for p, data := range committed {
		if err := base.MkdirAll(filepath.ToSlash(filepath.Dir(p))); err != nil {
			t.Fatal(err)
		}
		if err := base.WriteFile(p, data); err != nil {
			t.Fatal(err)
		}
	}
	res, err := New(WithNow(func() int64 { return 1 })).
		Check(Options{Folder: "/app", FS: base}, root)
	if err != nil {
		t.Fatal(err)
	}
	return res
}

// A FOLDER THAT MATCHES IS CLEAN, and Checked says what was compared.
func TestCheckMatchingFolderIsClean(t *testing.T) {
	res := checkMem(t, map[string][]byte{
		"/app/a.txt":     []byte("A\n"),
		"/app/sub/b.txt": []byte("B\n"),
	}, func(j *J) {
		j.File("a.txt", func(j *J) { j.Content("A\n") })
		j.Folder("sub", func(j *J) {
			j.File("b.txt", func(j *J) { j.Content("B\n") })
		})
	})

	if len(res.Drift) != 0 {
		t.Fatalf("drift: %+v", res.Drift)
	}
	if strings.Join(res.Checked, ",") != "a.txt,sub/b.txt" {
		t.Fatalf("checked: %v", res.Checked)
	}
	if res.Folder != "/app" {
		t.Fatalf("folder: %q", res.Folder)
	}
}

// THE DIFFERENCE COMES BACK AS DATA: both sides' bytes, per path.
func TestCheckDriftIsData(t *testing.T) {
	res := checkMem(t, map[string][]byte{
		"/app/same.txt":   []byte("S\n"),
		"/app/edited.txt": []byte("EDITED\n"),
	}, func(j *J) {
		j.File("same.txt", func(j *J) { j.Content("S\n") })
		j.File("edited.txt", func(j *J) { j.Content("GENERATED\n") })
		j.File("absent.txt", func(j *J) { j.Content("NEW\n") })
	})

	if len(res.Drift) != 2 {
		t.Fatalf("drift: %+v", res.Drift)
	}

	// Sorted by path.
	if res.Drift[0].Path != "absent.txt" || res.Drift[0].Kind != DriftMissing {
		t.Fatalf("first: %+v", res.Drift[0])
	}
	if string(res.Drift[0].Generated) != "NEW\n" || res.Drift[0].Existing != nil {
		t.Fatalf("missing carries generated bytes only: %+v", res.Drift[0])
	}

	if res.Drift[1].Path != "edited.txt" || res.Drift[1].Kind != DriftContent {
		t.Fatalf("second: %+v", res.Drift[1])
	}
	if string(res.Drift[1].Generated) != "GENERATED\n" ||
		string(res.Drift[1].Existing) != "EDITED\n" {
		t.Fatalf("content carries both sides: %+v", res.Drift[1])
	}
}

// A FILE THE GENERATORS DO NOT CLAIM IS LEFT ALONE.
func TestCheckUnclaimedFileIsLeftAlone(t *testing.T) {
	res := checkMem(t, map[string][]byte{
		"/app/a.txt":                 []byte("A\n"),
		"/app/hand-written.txt":      []byte("not mine\n"),
		"/app/sub/also-not-mine.txt": []byte("nor this\n"),
	}, func(j *J) {
		j.File("a.txt", func(j *J) { j.Content("A\n") })
	})

	if len(res.Drift) != 0 {
		t.Fatalf("drift: %+v", res.Drift)
	}
	if strings.Join(res.Checked, ",") != "a.txt" {
		t.Fatalf("checked: %v", res.Checked)
	}
}

// THE COMMITTED TREE CANNOT CHANGE WHAT THE GENERATORS PRODUCE, which
// is what the shadow is for. Exclude is the sharpest demonstration: on
// a real generate it means "leave this file alone if it already
// exists", so the file is never written and never compared.
func TestCheckCommittedTreeCannotInfluenceTheRun(t *testing.T) {
	gen := func(j *J) {
		j.FileP(FileProps{Name: "a.txt", Exclude: true}, func(j *J) {
			j.Content("GENERATED\n")
		})
	}

	res := checkMem(t, map[string][]byte{"/app/a.txt": []byte("STALE\n")}, gen)
	if len(res.Drift) != 1 || res.Drift[0].Kind != DriftContent {
		t.Fatalf("drift: %+v", res.Drift)
	}
	if string(res.Drift[0].Generated) != "GENERATED\n" ||
		string(res.Drift[0].Existing) != "STALE\n" {
		t.Fatalf("sides: %+v", res.Drift[0])
	}

	// The control: a plain generate DOES leave it alone.
	base := NewMemFS()
	_ = base.MkdirAll("/app")
	_ = base.WriteFile("/app/a.txt", []byte("STALE\n"))
	if _, err := New(WithNow(func() int64 { return 1 })).
		Generate(Options{Folder: "/app", FS: base}, gen); err != nil {
		t.Fatal(err)
	}
	got, _ := base.ReadFile("/app/a.txt")
	if string(got) != "STALE\n" {
		t.Fatalf("a plain generate should have left it: %q", got)
	}
}

// READS OUTSIDE THE FOLDER FALL THROUGH, so a Fragment source is read
// exactly as it would be on a write run.
func TestCheckReadsOutsideTheFolderFallThrough(t *testing.T) {
	res := checkMem(t, map[string][]byte{
		"/src/frag.txt": []byte("HEADER\n<[SLOT]>\nFOOTER\n"),
		"/app/f.txt":    []byte("HEADER\nBODY\n\nFOOTER\n"),
	}, func(j *J) {
		j.File("f.txt", func(j *J) {
			j.FragmentP(FragmentProps{From: "/src/frag.txt"}, func(j *J) {
				j.Content("BODY\n")
			})
		})
	})

	if len(res.Drift) != 0 {
		t.Fatalf("drift: %+v", res.Drift)
	}
}

// jostraca's OWN BOOKKEEPING is not output: the meta log carries
// timestamps, so it can never be byte-stable.
func TestCheckMetaFolderIsNotCompared(t *testing.T) {
	res := checkMem(t, map[string][]byte{"/app/a.txt": []byte("A\n")},
		func(j *J) { j.File("a.txt", func(j *J) { j.Content("A\n") }) })

	for _, p := range res.Checked {
		if strings.HasPrefix(p, ".jostraca") {
			t.Fatalf("meta folder compared: %v", res.Checked)
		}
	}
}

// A TREE GIVEN AS DATA reaches the same gate, which is the case the
// mode exists for.
func TestCheckComponentTreeAsData(t *testing.T) {
	const src = `[{"cmp":"File","props":{"name":"build.sh"},
	  "children":[{"cmp":"Content","props":{"src":"echo $$\"VER\"$$\n"}}]}]`

	committed := map[string][]byte{"/app/build.sh": []byte("echo $$\"VER\"$$\n")}

	// `raw`, so the `$$` is bytes rather than a render.
	root := treeRoot(t, src, CmpTreeOptions{Raw: true})
	if res := checkMem(t, committed, root); len(res.Drift) != 0 {
		t.Fatalf("raw should be clean: %+v", res.Drift)
	}

	// The control: `$$"VER"$$` renders its own literal with NO MODEL AT
	// ALL, which is the half `model: {}` never guarded.
	res := checkMem(t, committed, treeRoot(t, src))
	if len(res.Drift) != 1 || string(res.Drift[0].Generated) != "echo VER\n" {
		t.Fatalf("templated: %+v", res.Drift)
	}
}

// A MODE IS OUTPUT TOO, where the tree stated one.
//
// A REAL FILESYSTEM, because the mode is read back with Stat and the
// point is the bits a checkout actually has.
func TestCheckDeclaredMode(t *testing.T) {
	if isWindows() {
		t.Skip("no permission bits to compare")
	}
	dir := t.TempDir()
	out := filepath.Join(dir, "app")
	if err := os.MkdirAll(out, 0o755); err != nil {
		t.Fatal(err)
	}
	script := filepath.Join(out, "run.sh")
	body := "#!/bin/sh\necho hi\n"
	if err := os.WriteFile(script, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}

	gen := func(mode os.FileMode) func(*J) {
		return func(j *J) {
			j.FileP(FileProps{Name: "run.sh", Mode: mode}, func(j *J) {
				j.Content(body)
			})
		}
	}
	run := func(mode os.FileMode) CheckResult {
		res, err := New(WithNow(func() int64 { return 1 })).
			Check(Options{Folder: filepath.ToSlash(out)}, gen(mode))
		if err != nil {
			t.Fatal(err)
		}
		return res
	}

	drifted := run(0o755)
	if len(drifted.Drift) != 1 || drifted.Drift[0].Kind != DriftMode {
		t.Fatalf("mode drift: %+v", drifted.Drift)
	}
	if drifted.Drift[0].Mode != 0o755 || drifted.Drift[0].ExistingMode != 0o644 {
		t.Fatalf("bits: %+v", drifted.Drift[0])
	}

	// Clean once the bits match.
	if err := os.Chmod(script, 0o755); err != nil {
		t.Fatal(err)
	}
	if clean := run(0o755); len(clean.Drift) != 0 {
		t.Fatalf("should be clean: %+v", clean.Drift)
	}

	// A TREE THAT SAYS NOTHING ABOUT MODE holds the file to nothing,
	// because a run would leave the bits it found.
	if err := os.Chmod(script, 0o600); err != nil {
		t.Fatal(err)
	}
	if silent := run(0); len(silent.Drift) != 0 {
		t.Fatalf("an unstated mode is not compared: %+v", silent.Drift)
	}
}

// A CHECK WRITES NOTHING, ANYWHERE -- including the run that reports
// drift, and including the meta folder a generate would leave.
func TestCheckWritesNothing(t *testing.T) {
	dir := t.TempDir()
	out := filepath.Join(dir, "app")
	if err := os.MkdirAll(out, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(out, "a.txt"), []byte("STALE\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	listing := func() []string {
		entries, err := os.ReadDir(out)
		if err != nil {
			t.Fatal(err)
		}
		names := []string{}
		for _, e := range entries {
			names = append(names, e.Name())
		}
		sort.Strings(names)
		return names
	}
	before := strings.Join(listing(), ",")

	res, err := New(WithNow(func() int64 { return 1 })).
		Check(Options{Folder: filepath.ToSlash(out)}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("GENERATED\n") })
			j.File("b.txt", func(j *J) { j.Content("ALSO NEW\n") })
		})
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Drift) != 2 {
		t.Fatalf("drift: %+v", res.Drift)
	}

	if after := strings.Join(listing(), ","); after != before {
		t.Fatalf("a check left something behind: %q -> %q", before, after)
	}
	got, _ := os.ReadFile(filepath.Join(out, "a.txt"))
	if !bytes.Equal(got, []byte("STALE\n")) {
		t.Fatalf("a check rewrote the file it was asked about: %q", got)
	}
}

// EVERY SPELLING OF THE FOLDER FINDS THE SAME DRIFT, and `.` is the
// one that matters: it is the default, and it was the one that checked
// NOTHING and answered clean on a drifted tree. Every other case in
// this file passes an absolute "/app", which is why that survived.
func TestCheckFolderSpellings(t *testing.T) {
	for _, spelling := range []string{"ABS", "out", ".", "./out"} {
		t.Run(spelling, func(t *testing.T) {
			tmp := t.TempDir()
			out := filepath.Join(tmp, "out")
			if err := os.MkdirAll(out, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(
				filepath.Join(out, "a.txt"), []byte("STALE\n"), 0o644); err != nil {
				t.Fatal(err)
			}

			folder, at := spelling, tmp
			switch spelling {
			case "ABS":
				folder = out
			case ".":
				at = out
			}

			prev, err := os.Getwd()
			if err != nil {
				t.Fatal(err)
			}
			if err := os.Chdir(at); err != nil {
				t.Fatal(err)
			}
			defer os.Chdir(prev)

			res, err := New().Check(Options{Folder: folder}, func(j *J) {
				j.File("a.txt", func(j *J) { j.Content("FRESH\n") })
			})
			if err != nil {
				t.Fatal(err)
			}
			if strings.Join(res.Checked, ",") != "a.txt" {
				t.Fatalf("checked: %v", res.Checked)
			}
			if len(res.Drift) != 1 || res.Drift[0].Kind != DriftContent {
				t.Fatalf("drift: %+v", res.Drift)
			}
		})
	}
}

// A PROTECTED COMMITTED FILE MUST NOT HIDE DRIFT. The run reads the
// output path through the shadow, so it has to reach MEMORY: reaching
// the committed tree instead lets a `JOSTRACA_PROTECT` marker suppress
// the write, leaving nothing generated to compare and a clean answer
// for a file the generator asked to change. That is what an empty
// shadow root did, because `under` answered false for every relative
// path and true for every absolute one.
func TestCheckProtectedFileDoesNotHideDrift(t *testing.T) {
	for _, spelling := range []string{"ABS", "."} {
		t.Run(spelling, func(t *testing.T) {
			tmp := t.TempDir()
			out := filepath.Join(tmp, "out")
			if err := os.MkdirAll(out, 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(out, "a.txt"),
				[]byte("# JOSTRACA_PROTECT\nSTALE\n"), 0o644); err != nil {
				t.Fatal(err)
			}

			folder, at := out, tmp
			if spelling == "." {
				folder, at = ".", out
			}
			prev, err := os.Getwd()
			if err != nil {
				t.Fatal(err)
			}
			if err := os.Chdir(at); err != nil {
				t.Fatal(err)
			}
			defer os.Chdir(prev)

			res, err := New().Check(Options{Folder: folder}, func(j *J) {
				j.File("a.txt", func(j *J) { j.Content("FRESH\n") })
			})
			if err != nil {
				t.Fatal(err)
			}
			if len(res.Drift) != 1 || res.Drift[0].Kind != DriftContent {
				t.Fatalf("drift: %+v", res.Drift)
			}
		})
	}
}

// A PROJECT FOLDER ELSEWHERE IS NOT WALKED, and the walk returns. An
// absolute ProjectProps.Folder writes outside the checked folder, and
// MemFS exposes such a key under an empty root as an entry whose name
// is empty. Both ways of handling that are wrong and this holds
// against both: joining it with a separator walks a path that is not
// the folder's and finds nothing to compare, and taking the name alone
// re-enters the root and recurses until the stack goes.
func TestCheckAbsoluteProjectFolderOutsideRoot(t *testing.T) {
	tmp := t.TempDir()
	out := filepath.Join(tmp, "out")
	if err := os.MkdirAll(out, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(
		filepath.Join(out, "a.txt"), []byte("STALE\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	elsewhere := filepath.Join(tmp, "elsewhere")

	prev, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(out); err != nil {
		t.Fatal(err)
	}
	defer os.Chdir(prev)

	done := make(chan CheckResult, 1)
	go func() {
		res, cerr := New().Check(Options{Folder: "."}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("FRESH\n") })
			j.Project(ProjectProps{Folder: elsewhere}, func(j *J) {
				j.File("x.txt", func(j *J) { j.Content("X\n") })
			})
		})
		if cerr != nil {
			t.Error(cerr)
		}
		done <- res
	}()

	select {
	case res := <-done:
		if strings.Join(res.Checked, ",") != "a.txt" {
			t.Fatalf("checked: %v", res.Checked)
		}
		if len(res.Drift) != 1 || res.Drift[0].Kind != DriftContent {
			t.Fatalf("drift: %+v", res.Drift)
		}
	case <-time.After(20 * time.Second):
		t.Fatal("Check did not return: the walk is recursing")
	}
}

// memBase builds an in-memory committed tree.
func memBase(t *testing.T, committed map[string][]byte) *MemFS {
	t.Helper()
	base := NewMemFS()
	for p, data := range committed {
		if err := base.MkdirAll(filepath.ToSlash(filepath.Dir(p))); err != nil {
			t.Fatal(err)
		}
		if err := base.WriteFile(p, data); err != nil {
			t.Fatal(err)
		}
	}
	return base
}

// driftKinds flattens drift to "path:kind" for a one-line assertion.
func driftKinds(res CheckResult) string {
	out := []string{}
	for _, d := range res.Drift {
		out = append(out, d.Path+":"+string(d.Kind))
	}
	return strings.Join(out, ",")
}

// A GLOBAL DRYRUN DOES NOT BLANK A CHECK. The check forces Dryrun off
// for its own run, after the merge, and keeps every other global flag.
func TestCheckIgnoresGlobalDryrun(t *testing.T) {
	base := memBase(t, map[string][]byte{"/app/a.txt": []byte("STALE\n")})
	res, err := New(WithControl(Control{Dryrun: true})).
		Check(Options{Folder: "/app", FS: base}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("A\n") })
			j.File("b.txt", func(j *J) { j.Content("B\n") })
		})
	if err != nil {
		t.Fatal(err)
	}
	if strings.Join(res.Checked, ",") != "a.txt,b.txt" {
		t.Fatalf("checked: %v", res.Checked)
	}
	if got := driftKinds(res); got != "a.txt:content,b.txt:missing" {
		t.Fatalf("drift: %s", got)
	}
}

// A CHECK ALWAYS BUILDS. Build false, per call or global, would never
// reach the file handler and report every folder clean -- the one answer
// a gate must never give. Each case runs on an empty folder and on a
// stale committed file.
func TestCheckForcesBuildPerCall(t *testing.T) {
	off := false
	checkForcesBuild(t, New(), Options{Build: &off})
}

func TestCheckForcesBuildGlobal(t *testing.T) {
	checkForcesBuild(t, New(WithBuild(false)), Options{})
}

func checkForcesBuild(t *testing.T, j *J, opts Options) {
	t.Helper()
	root := func(j *J) { j.File("a.txt", func(j *J) { j.Content("A\n") }) }

	for _, tc := range []struct {
		name      string
		committed map[string][]byte
		want      string
	}{
		{"empty", map[string][]byte{}, "a.txt:missing"},
		{"stale", map[string][]byte{"/app/a.txt": []byte("STALE\n")}, "a.txt:content"},
	} {
		run := opts
		run.Folder = "/app"
		run.FS = memBase(t, tc.committed)
		res, err := j.Check(run, root)
		if err != nil {
			t.Fatal(err)
		}
		if strings.Join(res.Checked, ",") != "a.txt" {
			t.Fatalf("%s: checked: %v", tc.name, res.Checked)
		}
		if got := driftKinds(res); got != tc.want {
			t.Fatalf("%s: drift: %s", tc.name, got)
		}
		if strings.Join(res.Files.Written, ",") != "/app/a.txt" {
			t.Fatalf("%s: files: %+v", tc.name, res.Files)
		}
	}
}

// treeRoot decodes a component tree and returns its define-phase
// callback, failing the test rather than returning an error.
func treeRoot(t *testing.T, src string, opts ...CmpTreeOptions) func(*J) {
	t.Helper()
	var tree any
	if err := json.Unmarshal([]byte(src), &tree); err != nil {
		t.Fatal(err)
	}
	root, err := CmpTree(tree, opts...)
	if err != nil {
		t.Fatal(err)
	}
	return root
}

func isWindows() bool { return runtime.GOOS == "windows" }
