package jostraca

import (
	"encoding/json"
	"regexp"
	"testing"
)

// Cross-stack differential test for the COPY EXCLUDE surface.
//
// testdata/parity/copy_exclude_corpus.json is generated by
// ts/tools/copy-exclude-corpus.js and records TS's exact output tree for
// every combination of Copy placement, exclude value and on-disk state.
// This replays them through Go and asserts byte equality.
//
// The naming contract with the generator is the `place` field: the tree
// built below must mirror treeFor() in the generator exactly, or the two
// sides are answering different questions.
//
// If it fails, the stacks have drifted on how a Copy exclude is matched —
// which path it is compared against, whether naming a directory prunes
// the subtree, or whether a scalar String/RegExp is honoured at all. Do
// not regenerate the corpus to make it pass.

type copyExcludeCase struct {
	Name        string            `json:"name"`
	Place       string            `json:"place"`
	Exclude     json.RawMessage   `json:"exclude"`
	Seed        *string           `json:"seed"`
	Existing    map[string]any    `json:"existing"`
	Prepopulate map[string]string `json:"prepopulate"`
	Vol         map[string]string `json:"vol"`
	Error       bool              `json:"error"`
}

type copyExcludeFile struct {
	Scenario string            `json:"scenario"`
	Cases    []copyExcludeCase `json:"cases"`
}

// decodeCopyExclude mirrors decodeExclude() in the generator: the wire
// form is {"bool":b} | {"s":"..."} | {"re":"..."} | {"list":[...]}. A
// scalar and a one-element list are DIFFERENT values here on purpose —
// they take different arms of shouldIgnoreCopyPath, and the scalar arms
// were unreachable from TS until the Copy shape was widened.
func decodeCopyExclude(t *testing.T, raw json.RawMessage) any {
	t.Helper()
	if len(raw) == 0 || string(raw) == "null" {
		return nil
	}
	var m map[string]json.RawMessage
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("decode exclude %s: %v", raw, err)
	}
	if v, ok := m["bool"]; ok {
		var b bool
		if err := json.Unmarshal(v, &b); err != nil {
			t.Fatal(err)
		}
		return b
	}
	if v, ok := m["s"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			t.Fatal(err)
		}
		return s
	}
	if v, ok := m["re"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			t.Fatal(err)
		}
		return regexp.MustCompile(s)
	}
	if v, ok := m["list"]; ok {
		var items []json.RawMessage
		if err := json.Unmarshal(v, &items); err != nil {
			t.Fatal(err)
		}
		out := make([]any, 0, len(items))
		for _, it := range items {
			out = append(out, decodeCopyExclude(t, it))
		}
		return out
	}
	t.Fatalf("unknown exclude encoding: %s", raw)
	return nil
}

func TestCopyExcludeCorpusMatchesTS(t *testing.T) {
	body, err := parityFS.ReadFile("testdata/parity/copy_exclude_corpus.json")
	if err != nil {
		t.Fatal(err)
	}

	var corpus copyExcludeFile
	if err := json.Unmarshal(body, &corpus); err != nil {
		t.Fatalf("decode copy_exclude_corpus.json: %v", err)
	}
	if len(corpus.Cases) < 90 {
		t.Fatalf("corpus looks truncated: %d cases", len(corpus.Cases))
	}

	mismatch, errmismatch := 0, 0

	for _, c := range corpus.Cases {
		mem := NewMemFS()
		for k, v := range c.Prepopulate {
			if err := mem.WriteFile(k, []byte(v)); err != nil {
				t.Fatal(err)
			}
		}

		// An unknown placement means the generator grew a shape this
		// runner does not answer for. Fail loudly rather than quietly
		// replaying the wrong tree and reporting a pass.
		switch c.Place {
		case "top", "nested", "to", "file":
		default:
			t.Fatalf("%s: unknown placement %q; add it to this runner", c.Name, c.Place)
		}

		exclude := decodeCopyExclude(t, c.Exclude)

		props := func() CopyProps {
			p := CopyProps{From: "/src", Exclude: exclude}
			if c.Place == "file" {
				p.From = "/src/a.txt"
			}
			if c.Place == "to" {
				p.To = "dst"
			}
			return p
		}

		j := New(
			WithFS(mem),
			WithFolder("/out"),
			WithNow(func() int64 { return frozenNow }),
			WithModel(map[string]any{"v": "V"}),
		)

		_, gerr := j.Generate(
			Options{Existing: existingFromCorpus(t, c.Existing)},
			func(j *J) {
				j.Project(ProjectProps{Folder: "app"}, func(j *J) {
					j.File("marker.txt", func(j *J) { j.Content("MARKER\n") })
					if c.Place == "nested" {
						j.Folder("inner", func(j *J) { j.Copy(props()) })
						return
					}
					j.Copy(props())
				})
			})

		if c.Error {
			if gerr == nil {
				errmismatch++
				if errmismatch <= 10 {
					t.Errorf("%s: TS failed but Go succeeded", c.Name)
				}
				continue
			}
			// Both threw. Fall through to the tree comparison rather than
			// calling it a match here: a failed build still leaves whatever
			// it wrote before it stopped, and two stacks that throw at
			// DIFFERENT points leave different partial trees. Skipping the
			// comparison bought an assertion that both sides failed and
			// nothing about what they left behind. See PARITY_PLAN.md 2.1.
		} else if gerr != nil {
			errmismatch++
			if errmismatch <= 10 {
				t.Errorf("%s: TS succeeded but Go failed: %v", c.Name, gerr)
			}
			continue
		}

		got := map[string]string{}
		for k, v := range mem.Vol() {
			got[k] = string(v)
		}

		if !sameTree(got, c.Vol) {
			mismatch++
			if mismatch <= 12 {
				t.Errorf("%s: output tree differs\n go=%s\n ts=%s",
					c.Name, showTree(got), showTree(c.Vol))
			}
		}
	}

	if mismatch > 0 || errmismatch > 0 {
		t.Errorf("Copy exclude handling differs on %d/%d cases (+%d error mismatches)",
			mismatch, len(corpus.Cases), errmismatch)
	}
}
