package jostraca

import (
	"encoding/json"
	"testing"
)

// Cross-stack differential test for the diff/merge engine.
//
// testdata/parity/diff_corpus.json is generated by ts/tools/extract-parity.js
// and records TS's exact output for every case. This replays the same inputs
// through the Go engine and asserts byte equality.
//
// This is the test that actually holds the two implementations together.
// The scenario corpus exercises merge through a handful of well-behaved
// end-to-end cases, and that is precisely how the two stacks managed to
// disagree on ~72% of non-trivial merges without any test noticing: the
// shapes where the two algorithms differed were shapes nothing tested.
//
// If this fails, the stacks have drifted. Do not "fix" it by regenerating
// the corpus — that just records the drift as expected. Find which side
// changed and why.

type diffCorpusCase struct {
	Kind      string `json:"kind"`
	Generated string `json:"generated"`
	Baseline  string `json:"baseline"`
	Existing  string `json:"existing"`

	Content  string `json:"content"`
	Conflict bool   `json:"conflict"`
	Outcome  string `json:"outcome"`
}

type diffCorpus struct {
	Scenario string           `json:"scenario"`
	Labels   DiffLabels       `json:"labels"`
	Cases    []diffCorpusCase `json:"cases"`
}

func TestDiffCorpusMatchesTS(t *testing.T) {
	body, err := parityFS.ReadFile("testdata/parity/diff_corpus.json")
	if err != nil {
		t.Fatal(err)
	}

	var corpus diffCorpus
	if err := json.Unmarshal(body, &corpus); err != nil {
		t.Fatalf("decode diff_corpus.json: %v", err)
	}
	if len(corpus.Cases) < 500 {
		t.Fatalf("corpus looks truncated: %d cases", len(corpus.Cases))
	}

	spec := DiffSpec{Labels: &corpus.Labels}

	merges, diffs, conflicts := 0, 0, 0

	for i, c := range corpus.Cases {
		switch c.Kind {
		case "merge":
			merges++
			got := Merge(c.Generated, c.Baseline, c.Existing, spec)
			if got.Content != c.Content {
				t.Fatalf("case %d (merge): content differs\n generated=%q\n baseline=%q\n existing=%q\n go=%q\n ts=%q",
					i, c.Generated, c.Baseline, c.Existing, got.Content, c.Content)
			}
			if got.Conflict != c.Conflict {
				t.Errorf("case %d (merge): conflict go=%v ts=%v", i, got.Conflict, c.Conflict)
			}
			if string(got.Outcome) != c.Outcome {
				t.Errorf("case %d (merge): outcome go=%q ts=%q", i, got.Outcome, c.Outcome)
			}
			if got.Conflict {
				conflicts++
			}

		case "diff":
			diffs++
			got := Diff(c.Generated, c.Existing, spec)
			if got.Content != c.Content {
				t.Fatalf("case %d (diff): content differs\n generated=%q\n existing=%q\n go=%q\n ts=%q",
					i, c.Generated, c.Existing, got.Content, c.Content)
			}
			if got.Conflict != c.Conflict {
				t.Errorf("case %d (diff): conflict go=%v ts=%v", i, got.Conflict, c.Conflict)
			}
			if string(got.Outcome) != c.Outcome {
				t.Errorf("case %d (diff): outcome go=%q ts=%q", i, got.Outcome, c.Outcome)
			}

		default:
			t.Fatalf("case %d: unknown kind %q", i, c.Kind)
		}
	}

	// Guard against a corpus that technically passes but exercises nothing:
	// if the generator ever stopped producing conflicts, this test would go
	// green while testing only the easy paths.
	t.Logf("%d merge cases, %d diff cases, %d conflicting merges", merges, diffs, conflicts)
	if conflicts < 50 {
		t.Errorf("only %d conflicting merges in the corpus; the interesting "+
			"paths are barely covered", conflicts)
	}
}
