package jostraca

import (
	"bytes"
	"embed"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// corpusBytes is a corpus content value. The format is a JSON string when
// the bytes round-trip through UTF-8, and {"b64": "<base64>"} when they do
// not — see ts/tools/corpus-bytes.js. The corpus is GENERATED by TS and only
// READ here, so TS is the only side that ever decides which form to emit;
// Go only decodes, and so cannot disagree about what "valid UTF-8" means.
type corpusBytes []byte

func (c *corpusBytes) UnmarshalJSON(raw []byte) error {
	raw = bytes.TrimSpace(raw)
	if len(raw) == 0 {
		return fmt.Errorf("empty corpus content value")
	}
	if string(raw) == "null" {
		*c = nil
		return nil
	}
	if raw[0] == '"' {
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return err
		}
		*c = corpusBytes(s)
		return nil
	}
	var obj struct {
		B64 *string `json:"b64"`
	}
	if err := json.Unmarshal(raw, &obj); err != nil {
		return fmt.Errorf("corpus content value is neither a string nor "+
			`{"b64":...}: %s: %w`, raw, err)
	}
	if obj.B64 == nil {
		return fmt.Errorf("corpus content object has no b64 key: %s", raw)
	}
	dec, err := base64.StdEncoding.DecodeString(*obj.B64)
	if err != nil {
		return fmt.Errorf("corpus b64 content: %w", err)
	}
	*c = dec
	return nil
}

//go:embed testdata/parity/*.json
var parityFS embed.FS

// parityCase mirrors the JSON dumped by tools/extract-parity.js. It
// records the TS-side scenario name, options, prepopulated FS state,
// and the expected vol.toJSON() output produced by running the same
// component tree through the TS package.
type parityCase struct {
	Scenario    string                 `json:"scenario"`
	Opts        map[string]any         `json:"opts"`
	Prepopulate map[string]corpusBytes `json:"prepopulate"`
	// Error records whether the TS run threw. Asserted bidirectionally below,
	// so a scenario that fails in one stack and completes in the other is a
	// parity failure like any output difference. See docs/design/PARITY_PLAN.md 2.1.
	Error bool                   `json:"error"`
	Vol   map[string]corpusBytes `json:"vol"`

	// ErrorBody is the TS message body of a failing run, with the wrapper
	// and an embedded filesystem error normalised as parityErrorBody does.
	ErrorBody string `json:"errorBody"`

	// Files is the seven files lists the TS run reported, or nil when it
	// threw.
	Files *Files `json:"files"`

	// Audit is the TS run's audit trail, each err reduced to its message.
	Audit []any `json:"audit"`
}

// scenarioRunner builds the component tree for a named scenario. The
// runners here mirror the tree shapes in tools/extract-parity.js so a
// byte-equal parity assertion is meaningful.
var scenarioRunners = map[string]func(j *J){
	// Fragment eject: the source is trimmed to the region between the markers.
	// See docs/design/PARITY_PLAN.md 3.
	"fragment_eject": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("part.txt", func(j *J) {
				j.Fragment(FragmentProps{
					From:  "/templates/whole.txt",
					Eject: []any{"START\n", "END\n"},
				}, nil)
			})
		})
	},
	// Fails in BOTH stacks, which is the point: it exercises the `error` field
	// end to end. TS rejects `from` through the shape Check, Go at
	// builder.go. See docs/design/PARITY_PLAN.md 2.1.
	"fragment_missing_from_errors": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("index.html", func(j *J) {
				j.Fragment(FragmentProps{From: "/templates/does-not-exist.html"}, nil)
			})
		})
	},
	// Two more both-stacks-fail rows, added with the same reasoning as the
	// one above: one row does not gate a class. Measured on both sides
	// before being added -- they agree on the error AND on the partial tree,
	// which assertVol below checks even for an error case.
	//
	// The Copy fails before anything is written; the Inject fails in its
	// after-hook, by which time the project folder exists. That second row
	// is the one that pins a NON-EMPTY tree on an error path.
	// See docs/design/PARITY_PLAN.md 2.1.
	"copy_missing_source_errors": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/src/does-not-exist.txt", To: "a.txt"})
		})
	},
	"inject_missing_target_errors": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("does-not-exist.txt", func(j *J) { j.Content("new content") })
		})
	},
	// Issue #30: a binary Copy onto a byte-identical target with
	// bin.preserve must write no backup. Go has always compared with
	// bytes.Equal; TS compared a Buffer against a string and backed up
	// every time. See docs/design/PARITY_PLAN.md 3.
	"binary_copy_identical_no_backup": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/src/mod.wasm", To: "mod.wasm"})
		})
	},
	// A user component as a direct Fragment child, with an unnamed <[SLOT]>
	// to receive it. Its body runs once, in the default-slot replay, and its
	// content is spliced at the marker -- the same as TS. Before #29 was
	// closed, `j.Cmp` allocated no node, so the Fragment filter never saw
	// this child and its body ran once per replay pass instead.
	"fragment_cmp_child_default_slot": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) {
				j.FragmentP(FragmentProps{From: "/tpl/f.txt"}, func(j *J) {
					j.Cmp("Counter", func(j *J) { j.Content("H") })
					j.SlotP(SlotProps{Name: "s0"}, func(j *J) { j.Content("S0") })
				})
			})
		})
	},
	"quickstart": func(j *J) {
		j.Project(ProjectProps{Folder: "my-app"}, func(j *J) {
			j.Folder("src", func(j *J) {
				j.File("index.js", func(j *J) {
					j.Content("console.log(\"hello world\")\n")
				})
			})
			j.File("package.json", func(j *J) {
				j.Content("{ \"name\": \"my-app\" }\n")
			})
		})
	},
	"template_model": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("config.txt", func(j *J) {
				j.Content("App: $$app.name$$ v$$app.version$$\n")
			})
		})
	},
	"fragment_slot": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("index.html", func(j *J) {
				j.Fragment(FragmentProps{From: "/templates/page.html"}, func(j *J) {
					j.Slot("head", func(j *J) { j.Content("<title>X</title>") })
					j.Slot("body", func(j *J) { j.Content("<h1>Hello</h1>") })
				})
			})
		})
	},
	"inject_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("new content") })
		})
	},
	"copy_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/tpl/hello.txt"})
		})
	},
	// A Copy nested INSIDE a File, the shape no fixture covered and the reason
	// #39 survived: TS displaced buildctx.current.file and never put it back,
	// so the enclosing file was never written and its earlier content was lost.
	// Go was correct throughout; this pins both sides on the same output.
	"copy_in_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) {
				j.Content("BEFORE\n")
				j.Copy(CopyProps{From: "/tpl/hello.txt"})
				j.Content("AFTER\n")
			})
		})
	},
	// The same defect one component along, and the more destructive of the
	// two: the enclosing File wrote its own content over the Inject's TARGET.
	// An Inject contributes no text to the file around it.
	"inject_in_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) {
				j.Content("BEFORE\n")
				j.Inject("foo.txt", func(j *J) { j.Content("new content") })
				j.Content("AFTER\n")
			})
		})
	},
	"list_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.List([]any{"a", "b", "c"}, func(j *J, it ListItemProps) {
					j.Line(it.Item.(string))
				})
			})
		})
	},
	// The `{item}` macro and `indent` a List hands its body. ListP used to
	// take no props object at all, so a body interpolating {item.n} emitted
	// the macro verbatim and ListProps.Indent was declared and never read.
	// The single list_basic fixture used a plain body, which is how #40
	// survived. Every quiet limit is exercised: a bare {item}, a $-suffixed
	// key, an unresolved path, and a near-miss left in place.
	"list_item_macro": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.List([]any{
					map[string]any{"n": "p", "d": map[string]any{"e": "X"}},
					map[string]any{"n": "q", "d": map[string]any{"e": "Y"}},
				}, func(j *J, it ListItemProps) {
					j.ContentP(ContentProps{
						Src: "n={item.n} deep={item.d.e} bare={item} " +
							"dollar={item.index$} miss={item.zz} near={itemx}\n",
						Replace: it.Replace,
					})
				})
			})
			j.File("indent.txt", func(j *J) {
				j.ListP(ListProps{
					Item: []any{
						map[string]any{"n": "p"},
						map[string]any{"n": "q"},
					},
					Indent: ">>",
					NoLine: true,
				}, func(j *J, it ListItemProps) {
					j.ContentP(ContentProps{
						Src: "n={item.n}\n", Replace: it.Replace, Indent: it.Indent,
					})
				})
			})
			// Value formatting. A function replacement JSONifies objects and
			// arrays on both stacks now; TS used to emit "[object Object]"
			// and "1,2", which a ReplaceFunc cannot reproduce - it returns a
			// string, so there is no JS coercion to inherit.
			j.File("values.txt", func(j *J) {
				j.ListP(ListProps{
					Item: []any{
						map[string]any{"v": 42.0},
						map[string]any{"v": 1.5},
						map[string]any{"v": true},
						map[string]any{"v": nil},
						map[string]any{"v": map[string]any{"a": 1.0}},
						map[string]any{"v": []any{1.0, 2.0}},
					},
					NoLine: true,
				}, func(j *J, it ListItemProps) {
					j.ContentP(ContentProps{Src: "v={item.v}\n", Replace: it.Replace})
				})
			})
		})
	},
	// Directory-only state: an EMPTY Folder. TS's FolderOp materialised one
	// and folderBefore did not, and nothing could see the difference until
	// Vol() learned to report directories - it returned files only, so a
	// snapshot recording TS's null entry had nothing to compare against.
	// A directory appears only while EMPTY, so `full` is absent and
	// `empty` and `outer/inner` are null. #41.
	"empty_folder": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Folder("empty", func(j *J) {})
			j.Folder("full", func(j *J) {
				j.File("a.txt", func(j *J) { j.Content("A\n") })
			})
			j.Folder("outer", func(j *J) {
				j.Folder("inner", func(j *J) {})
			})
		})
	},
	// A STRING child of TS's List, which used to emit nothing at all (#44).
	// Go has no string-children concept, so this writes out the explicit body
	// the shorthand desugars to -- which is the point. The two spellings have
	// to produce the same bytes, or the shorthand means something TS-only.
	"list_string_child": func(j *J) {
		items := []any{
			map[string]any{"n": "p"},
			map[string]any{"n": "q"},
		}
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.ListP(ListProps{Item: items, Indent: ">>"},
					func(j *J, it ListItemProps) {
						j.ContentP(ContentProps{
							Src: "n={item.n}\n", Replace: it.Replace, Indent: it.Indent,
						})
					})
			})
			// Two children, to pin that they iterate INSIDE the item loop.
			j.File("two.txt", func(j *J) {
				j.ListP(ListProps{Item: items, NoLine: true},
					func(j *J, it ListItemProps) {
						j.ContentP(ContentProps{Src: "a={item.n}\n", Replace: it.Replace})
						j.ContentP(ContentProps{Src: "b={item.n}\n", Replace: it.Replace})
					})
			})
		})
	},
	"line_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.Line("hello")
			})
		})
	},
	"protect": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("cfg.txt", func(j *J) { j.Content("regenerated\n") })
		})
	},
	"unchanged": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("A") })
		})
	},
	"preserve_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"present_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"diff_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"happy_multifile": func(j *J) {
		j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
			j.Folder("js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// custom-foo\n") })
				j.File("bar.js", func(j *J) { j.Content("// custom-bar\n") })
			})
			j.Folder("go", func(j *J) {
				j.File("zed.go", func(j *J) { j.Content("// custom-zed\n") })
			})
		})
	},
	"fragment_nested_in_slot": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/f.txt"}, func(j *J) {
					j.Slot("s", func(j *J) {
						j.Fragment(FragmentProps{From: "/f2.txt"}, func(j *J) {})
						j.Content("DIRECT")
					})
				})
			})
		})
	},
	"fragment_relative_from": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Folder("sub", func(j *J) {
				j.File("out.txt", func(j *J) {
					j.Fragment(FragmentProps{From: "frag.txt"}, func(j *J) {})
				})
			})
		})
	},
	"copy_ignore_text": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm"})
		})
	},
	"preserve_and_diff": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"protect_and_present": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"inject_two_blocks": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"inject_stray_end_marker": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	// Inject exclude is JavaScript truthiness: any truthy value skips it.
	"inject_exclude_string":     injectExcludeRunner("other"),
	"inject_exclude_emptyarray": injectExcludeRunner([]any{}),
	"inject_exclude_list":       injectExcludeRunner([]any{"other"}),
	"inject_exclude_object":     injectExcludeRunner(map[string]any{}),
	// An Inject's children build the region as they would build a File.
	"inject_fragment_child": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("t.txt", func(j *J) {
				j.Content("c1;")
				j.Fragment(FragmentProps{From: "/tpl/model.txt"}, nil)
				j.Content("c2;")
			})
		})
	},
	"inject_copy_child": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("t.txt", func(j *J) {
				j.Content("pre;")
				j.CopyFiles(CopyFilesProps{From: "/tpl/single.txt", To: "copied.txt"})
				j.Content("post;")
			})
		})
	},
	// A Folder or a Project inside a File never becomes the current file.
	"folder_and_project_in_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("f.txt", func(j *J) {
				j.Content("1")
				j.Folder("d", func(j *J) { j.Content("x") })
				j.Content("2")
			})
			j.File("g.txt", func(j *J) {
				j.Content("1")
				j.Project(ProjectProps{Folder: "p"}, func(j *J) { j.Content("y") })
				j.Content("2")
			})
			j.File("h.txt", func(j *J) {
				j.Content("1")
				j.Folder("e", func(j *J) { j.Copy(CopyProps{From: "/src/c.txt", To: "c2.txt"}) })
				j.Folder("k", func(j *J) {
					j.Fragment(FragmentProps{From: "/tm/f.txt"}, func(j *J) { j.Content("S") })
				})
				j.Content("2")
			})
			j.File("j.txt", func(j *J) {
				j.Content("1")
				j.Folder("m", func(j *J) {
					j.File("inner.txt", func(j *J) { j.Content("I") })
					j.Content("z")
				})
				j.Folder(".", func(j *J) { j.Inject("inj.txt", func(j *J) { j.Content("NEW") }) })
				j.Content("2")
			})
		})
	},
	"file_in_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("outer.txt", func(j *J) {
				j.Content("1")
				j.File("inner.txt", func(j *J) { j.Content("2") })
				j.Content("3")
			})
			j.File("outer2.txt", func(j *J) {
				j.Content("1")
				j.Folder("sub", func(j *J) {
					j.File("inner.txt", func(j *J) { j.Content("2") })
				})
				j.Content("3")
			})
			j.File("next.txt", func(j *J) { j.Content("next") })
		})
	},
	// A Project's folder applies to its own subtree only (#26).
	"project_nested_in_folder": func(j *J) {
		j.Project(ProjectProps{Folder: "."}, func(j *J) {
			j.Folder("a", func(j *J) {
				j.Project(ProjectProps{Folder: "p2"}, func(j *J) {
					j.File("x.txt", func(j *J) { j.Content("x") })
				})
			})
			j.File("y.txt", func(j *J) { j.Content("y") })
		})
	},
	"project_nested_two_folders": func(j *J) {
		j.Project(ProjectProps{Folder: "."}, func(j *J) {
			j.Folder("a", func(j *J) {
				j.Folder("b", func(j *J) {
					j.Project(ProjectProps{Folder: "p2"}, func(j *J) {
						j.File("x.txt", func(j *J) { j.Content("x") })
					})
				})
				j.File("z.txt", func(j *J) { j.Content("z") })
			})
			j.File("y.txt", func(j *J) { j.Content("y") })
		})
	},
	"project_then_sibling_file": func(j *J) {
		j.Project(ProjectProps{Folder: "."}, func(j *J) {
			j.Project(ProjectProps{Folder: "p"}, func(j *J) {
				j.File("a.txt", func(j *J) { j.Content("a") })
			})
			j.File("y.txt", func(j *J) { j.Content("y") })
		})
	},
	"two_sibling_projects": func(j *J) {
		j.Project(ProjectProps{Folder: "a"}, func(j *J) {
			j.File("x.txt", func(j *J) { j.Content("x") })
		})
		j.Project(ProjectProps{Folder: "b"}, func(j *J) {
			j.File("y.txt", func(j *J) { j.Content("y") })
		})
	},
	// A Fragment is templated once.
	"frag_double_template": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("double.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/double.txt"}, nil)
				j.Content("content:$$a$$\n")
			})
			j.File("r1.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/replace.txt",
					Replace: map[string]any{"FOO": "$$b$$", "BAR": "bar"}}, nil)
			})
			j.File("r2.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/replace.txt",
					Replace: map[string]any{"FOO": `$$"q"$$`,
						"BAR": func() string { return "$$name$$" }}}, nil)
			})
		})
	},
	// A Fragment renders when it is called.
	"frag_nonslot_no_default_error": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("ok.txt", func(j *J) { j.Content("ok") })
			j.File("n.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/noslot.txt"}, func(j *J) { j.Content("lost") })
			})
		})
	},
	"frag_template_error": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("first.txt", func(j *J) { j.Content("first") })
			j.File("e.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/model.txt",
					Replace: map[string]any{"/x*/": "y"}}, nil)
			})
		})
	},
	"frag_slot_body_counter": func(j *J) {
		n := 0
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("c.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/twice.txt"}, func(j *J) {
					n++
					j.Slot("a", func(j *J) { j.Content(fmt.Sprintf("a%d", n)) })
					j.Content(fmt.Sprintf("d%d", n))
				})
				j.Content(fmt.Sprintf("after=%d\n", n))
			})
		})
	},
	"frag_reads_generated": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("tpl.txt", func(j *J) { j.Content("NEW $$name$$ <[SLOT]>\n") })
			j.File("use.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "app/tpl.txt"}, func(j *J) { j.Content("S") })
			})
		})
	},
	"frag_slot_copy": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("f.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/slot.txt"}, func(j *J) {
					j.Slot("s", func(j *J) {
						j.Content("pre;")
						j.Copy(CopyProps{From: "/tm/c.txt", To: "c.txt"})
						j.Content("post;")
					})
				})
			})
		})
	},
	"frag_replace_fn_emits": func(j *J) {
		around := func(j *J, body func(*J)) {
			j.Cmp("Around", func(j *J) {
				j.Content("<")
				body(j)
				j.Content(">")
			})
		}
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("f.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/replace.txt", Replace: map[string]any{
					"FOO": func(j *J) {
						j.ListItemsP(ListItemsProps{
							Item:   []any{map[string]any{"n": 1}, map[string]any{"n": 2}},
							NoLine: true,
						}, func(j *J, it ListItemProps) {
							j.ContentP(ContentProps{Src: "[{item.n}]", Replace: it.Replace})
						})
					},
					"BAR": func(j *J) { j.Line("bar") },
				}}, nil)
				j.Fragment(FragmentProps{From: "/tm/replace.txt", Replace: map[string]any{
					"FOO": func(j *J) { j.Fragment(FragmentProps{From: "/tm/model.txt"}, nil) },
					"BAR": func(j *J) { around(j, func(j *J) { j.Content("w") }) },
				}}, nil)
			})
		})
	},
	// A wrongly typed Fragment or CopyFiles prop stops the run before
	// anything is written.
	"copy_exclude_number": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("first.txt", func(j *J) { j.Content("first") })
			j.Copy(CopyProps{From: "/tm/tree", To: "n", Exclude: 5})
		})
	},
	"frag_indent_bool": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("first.txt", func(j *J) { j.Content("first") })
			j.File("b.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tm/model.txt", Indent: true}, nil)
			})
		})
	},
	// A single-file Copy spliced into a File or an Inject carries its replace.
	"copy_in_file_replace": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("host.txt", func(j *J) {
				j.Content("pre\n")
				j.Copy(CopyProps{From: "/tpl/single.txt", To: "spliced.txt",
					Replace: map[string]any{"FOO": "bar"}})
				j.Content("post\n")
			})
			j.Inject("t.txt", func(j *J) {
				j.Content("pre;")
				j.Copy(CopyProps{From: "/tpl/single.txt", To: "spliced2.txt",
					Replace: map[string]any{"FOO": "bar"}})
				j.Content("post;")
			})
		})
	},
	// A plain replace value formats as a replace function's return does.
	"replace_values": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("c.txt", func(j *J) {
				for _, c := range []struct {
					src string
					v   any
				}{
					{"zero=FOO;", 0}, {"false=FOO;", false}, {"null=FOO;", nil},
					{"empty=FOO;", ""}, {"arr=FOO;", []any{1, "a"}},
					{"obj=FOO;", map[string]any{"b": 1, "a": []any{2, "x"}}},
					{"big=FOO;", 1e6}, {"huge=FOO;", 1e21}, {"tiny=FOO;", 1e-7},
					{"neg=FOO\n", -5},
				} {
					j.ContentP(ContentProps{Src: c.src, Replace: map[string]any{"FOO": c.v}})
				}
				j.LineP(ContentProps{Src: "line=FOO", Replace: map[string]any{"FOO": 123456789012}})
			})
			j.File("f.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/tpl/frag.txt", Replace: map[string]any{
					"FOO": 5, "BAR": map[string]any{"k": 1, "a": []any{true}}}}, nil)
				j.Fragment(FragmentProps{From: "/tpl/frag.txt", Replace: map[string]any{
					"FOO": false, "BAR": 2.5e-8}}, nil)
				j.Fragment(FragmentProps{From: "/tpl/frag.txt", Replace: map[string]any{
					"FOO": func() string { return "fn" },
					"BAR": func() any { return nil }}}, nil)
			})
			j.Copy(CopyProps{From: "/tpl/copy.txt", Replace: map[string]any{"FOO": 123456789012}})
			j.Copy(CopyProps{From: "/tpl/dir", To: "r", Replace: map[string]any{
				"/C/": "Z", "World": map[string]any{"o": 1}}})
		})
	},
	// A string indent is inserted literally, and a negative count adds
	// nothing.
	"indent_edges": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("d.txt", func(j *J) {
				j.ContentP(ContentProps{Src: "a\nb\n", Indent: "$$ "})
				j.ContentP(ContentProps{Src: "c\n", Indent: "$& "})
				j.ContentP(ContentProps{Src: "d\n", Indent: "$1|"})
				j.LineP(ContentProps{Src: "e", Indent: "$'"})
				j.ContentP(ContentProps{Src: "f\n", Indent: -1})
				j.ContentP(ContentProps{Src: "g\n", Indent: 2.7})
				j.Fragment(FragmentProps{From: "/tpl/frag.txt", Indent: "$$"}, nil)
				j.Fragment(FragmentProps{From: "/tpl/frag.txt", Indent: -3}, nil)
			})
		})
	},
	// A directory Copy walks its source by UTF-16 code unit.
	"copy_order": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/tpl/order"})
		})
	},
	// The meta log writes '&', '<', '>' and U+2028 raw, as JSON.stringify.
	"meta_log_raw_quotes": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			for _, n := range []string{"a&b.txt", "x<y>.txt", "u\u2028v.txt"} {
				j.File(n, func(j *J) { j.Content("A\n") })
			}
		})
	},
	// A Slot outside a Fragment is transparent.
	"slot_outside_fragment": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("s.txt", func(j *J) {
				j.Content("a")
				j.SlotP(SlotProps{Name: "x"}, func(j *J) { j.Content("S") })
				j.Content("b")
				j.SlotP(SlotProps{}, func(j *J) { j.Content("U") })
				j.SlotP(SlotProps{Name: "n"}, func(j *J) {
					j.Content("N")
					j.SlotP(SlotProps{Name: "m"}, func(j *J) { j.Content("M") })
				})
				j.Cmp("Wrap", func(j *J) {
					j.SlotP(SlotProps{Name: "w"}, func(j *J) { j.Content("W") })
				})
			})
			j.Inject("t.txt", func(j *J) {
				j.Content("i")
				j.SlotP(SlotProps{Name: "x"}, func(j *J) { j.Content("S") })
				j.Content("j")
			})
		})
	},
	// A File exclude names the component path, never the Project folder.
	"file_exclude": func(j *J) {
		j.Project(ProjectProps{Name: "pn"}, func(j *J) {
			j.FileP(FileProps{Name: "keep.txt", Exclude: "pn/keep.txt"},
				func(j *J) { j.Content("NEW") })
			j.Folder("sub", func(j *J) {
				j.FileP(FileProps{Name: "keep2.txt", Exclude: []any{"pn/sub/keep2.txt"}},
					func(j *J) { j.Content("NEW") })
			})
			j.FileP(FileProps{Name: "a.txt", Exclude: "a.txt"},
				func(j *J) { j.Content("NEW") })
			j.FileP(FileProps{Name: "b.txt", Exclude: []any{regexp.MustCompile("b")}},
				func(j *J) { j.Content("NEW") })
			j.FileP(FileProps{Name: "c.txt", Exclude: true},
				func(j *J) { j.Content("NEW") })
		})
	},
	"file_exclude_project_folder": func(j *J) {
		j.Project(ProjectProps{Folder: "x"}, func(j *J) {
			j.FileP(FileProps{Name: "a.txt", Exclude: "x/a.txt"},
				func(j *J) { j.Content("NEW") })
			j.FileP(FileProps{Name: "b.txt", Exclude: "b.txt"},
				func(j *J) { j.Content("NEW") })
		})
	},
	// A backslash in an output-path component is a separator.
	"backslash_names": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a\\b.txt", func(j *J) { j.Content("B") })
			j.Folder("x\\y", func(j *J) {
				j.File("a.txt", func(j *J) { j.Content("A") })
			})
			j.Inject("a\\t.txt", func(j *J) { j.Content("NEW") })
		})
		j.Project(ProjectProps{Folder: "p\\q"}, func(j *J) {
			j.File("c.txt", func(j *J) { j.Content("C") })
		})
	},
	// One path saved twice in a run.
	"inject_after_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("t.txt", func(j *J) { j.Content(parityMarked) })
			j.Inject("t.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"inject_twice_same_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("t.txt", func(j *J) { j.Content("ONE") })
			j.Inject("t.txt", func(j *J) { j.Content("TWO") })
		})
	},
	"copy_then_file_same": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.CopyFiles(CopyFilesProps{From: "/src/single.txt"})
			j.File("single.txt", func(j *J) { j.Content("F\n") })
		})
	},
	"file_then_copy_same": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("single.txt", func(j *J) { j.Content("F\n") })
			j.CopyFiles(CopyFilesProps{From: "/src/single.txt"})
		})
	},
	"file_g_h_inject_g": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("g.txt", func(j *J) { j.Content(parityMarked) })
			j.File("h.txt", func(j *J) { j.Content("H") })
			j.Inject("g.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"inject_no_markers": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"no_project_file": func(j *J) {
		j.File("x.txt", func(j *J) { j.Content("hi\n") })
	},
	"dotfile_preserve": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File(".env", func(j *J) { j.Content("NEW-ENV\n") })
			j.File(".npmrc", func(j *J) { j.Content("NEW-NPMRC\n") })
		})
	},
	"content_empty_folder": func(j *J) {
		j.Folder("", func(j *J) {
			j.File("foo.txt", func(j *J) { j.Content("A") })
		})
	},
	"basic_copy": func(j *J) {
		j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
			j.Folder("js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// custom-foo\n") })
				j.Copy(CopyProps{From: "/tm/bar.txt", To: "bar.txt"})
				j.Copy(CopyProps{From: "/tm/sub"})
			})
		})
	},
	"copy_binary_unlisted_ext": func(j *J) {
		j.Project(ProjectProps{Folder: "p"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm"})
		})
	},
	"existing_bin_classification": func(j *J) {
		j.Project(ProjectProps{Folder: "p"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm/logo.png", To: "logo.png"})
			j.Copy(CopyProps{From: "/tm/mod.wasm", To: "mod.wasm"})
			j.Copy(CopyProps{From: "/tm/readme.txt", To: "readme.txt"})
			j.File("icon.png", func(j *J) { j.Content("NEW-ICON\n") })
		})
	},
	"absolute_paths": func(j *J) {
		// Project.Folder is absolute; Folder name has a leading /.
		// Both must compose into a clean /top/sdk/code/js path even
		// though the global folder option is /top.
		j.Project(ProjectProps{Folder: "/top/sdk"}, func(j *J) {
			j.Folder("/code/js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// foo:0\n") })
			})
		})
	},
}

const parityMarked = "a\n#--START--#\nold\n#--END--#\nz\n"

func injectExcludeRunner(exclude any) func(j *J) {
	return func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.InjectP(InjectProps{Name: "t.txt", Exclude: exclude},
				func(j *J) { j.Content("NEW") })
		})
	}
}

// scenarioOptions returns per-scenario Options additions; merged on top
// of the WithFS+WithFolder+WithNow base.
func scenarioOptions(scenario string) []Option {
	switch scenario {
	case "template_model":
		return []Option{WithModel(map[string]any{
			"app": map[string]any{"name": "Acme", "version": "1.0.0"},
		})}
	case "copy_file", "copy_in_file", "inject_fragment_child", "inject_copy_child",
		"frag_nonslot_no_default_error", "frag_template_error", "frag_reads_generated",
		"frag_slot_copy", "frag_replace_fn_emits", "frag_indent_bool", "copy_in_file_replace":
		return []Option{WithModel(map[string]any{"name": "World"})}
	case "folder_and_project_in_file", "replace_values":
		return []Option{WithModel(map[string]any{"name": "N"})}
	case "frag_double_template":
		return []Option{WithModel(map[string]any{"a": "$$b$$", "b": "X", "name": "N"})}
	case "preserve_mode", "dotfile_preserve":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Preserve: &t}})}
	case "binary_copy_identical_no_backup":
		t := true
		return []Option{WithExisting(Existing{Bin: ExistingBin{Preserve: &t}})}
	case "present_mode":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Present: &t}})}
	case "diff_mode":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Diff: &t}})}
	case "preserve_and_diff":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Preserve: &t, Diff: &t}})}
	case "protect_and_present":
		t, f := true, false
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Write: &f, Present: &t}})}
	case "basic_copy":
		return []Option{WithModel(map[string]any{"x": map[string]any{"y": "Y", "z": "Z"}})}
	case "copy_ignore_text", "copy_binary_unlisted_ext":
		return []Option{WithModel(map[string]any{"v": "V"})}
	case "existing_bin_classification":
		t := true
		return []Option{
			WithModel(map[string]any{"v": "V"}),
			WithExisting(Existing{
				Txt: ExistingTxt{Diff: &t},
				Bin: ExistingBin{Preserve: &t},
			}),
		}
	case "absolute_paths":
		return []Option{WithFolder("/top")}
	}
	return nil
}

const frozenNow int64 = 1735689600000

func TestParityScenarios(t *testing.T) {
	entries, err := parityFS.ReadDir("testdata/parity")
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		// Phase-shaped corpora are owned by their dedicated test functions
		// (e.g. merge_retain.json drives TestMergeRetainSequence). They
		// don't fit the {opts, prepopulate, vol} runner shape.
		if _, isPhaseShaped := phaseShapedCorpora[name]; isPhaseShaped {
			continue
		}
		t.Run(name, func(t *testing.T) {
			runParityCase(t, "testdata/parity/"+e.Name(), name)
		})
	}
}

func runParityCase(t *testing.T, path, name string) {
	t.Helper()
	body, err := parityFS.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var c parityCase
	if err := json.Unmarshal(body, &c); err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}

	// Multi-phase scenarios live in scenarioMultiPhase and own their
	// own MemFS lifecycle.
	if mp, ok := scenarioMultiPhase[name]; ok {
		mem := mp(t)
		assertVol(t, mem, c.Vol)
		return
	}

	runner, ok := scenarioRunners[name]
	if !ok {
		if reason, known := knownParityGaps[name]; known {
			t.Skipf("known parity gap: %s", reason)
			return
		}
		// A missing runner is a parity gap, not a non-event: the TS side has
		// a scenario the Go port does not answer for. Fail loudly, and use
		// knownParityGaps to carry a deliberate, documented exemption.
		t.Fatalf("scenario %s has no Go runner; add one to scenarioRunners "+
			"(or record a deliberate exemption in knownParityGaps)", name)
		return
	}

	mem := NewMemFS()
	for k, v := range c.Prepopulate {
		_ = mem.WriteFile(k, []byte(v))
	}

	opts := []Option{WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow })}
	opts = append(opts, scenarioOptions(name)...)
	j := New(opts...)

	res, gerr := j.Generate(Options{}, runner)

	if c.Error {
		if gerr == nil {
			t.Fatalf("TS failed but Go succeeded")
		}
		if got := parityErrorBody(gerr); got != c.ErrorBody {
			t.Errorf("error body\n got %q\nwant %q", got, c.ErrorBody)
		}
	} else if gerr != nil {
		t.Fatalf("TS succeeded but Go failed: %v", gerr)
	}

	if c.Files != nil {
		assertFiles(t, res.Files, *c.Files)
	}
	if c.Audit != nil {
		assertAudit(t, res.Audit(), c.Audit)
	}
	assertVol(t, mem, c.Vol)
}

// parityErrorBody is the part of a Go refusal the corpus records: the
// NodeError's own message, with an embedded filesystem error cut to
// `(threw: <os>)`, as extract-parity.js cuts TS's.
func parityErrorBody(err error) string {
	body := err.Error()
	var ne *NodeError
	if errors.As(err, &ne) {
		body = ne.Err.Error()
	}
	if i := strings.Index(body, "(threw: "); i >= 0 {
		body = body[:i] + "(threw: <os>)"
	}
	return body
}

// auditJSON renders a Go audit trail in the recorded [tag, data] form. An
// err compares by presence only: its text is the host's.
func auditJSON(t *testing.T, a Audit) []any {
	t.Helper()
	out := make([]any, 0, len(a))
	for _, e := range a {
		data := map[string]any{}
		for k, v := range e.Data {
			if k == "err" {
				v = "<err>"
			}
			data[k] = v
		}
		out = append(out, []any{e.Tag, data})
	}
	b, err := json.Marshal(out)
	if err != nil {
		t.Fatal(err)
	}
	var norm []any
	_ = json.Unmarshal(b, &norm)
	return norm
}

// auditPair renders a Go audit trail and a recorded TS one comparably,
// entry by entry and in order, each err compared by presence.
func auditPair(t *testing.T, got Audit, want []any) (string, string) {
	t.Helper()
	for _, e := range want {
		pair, _ := e.([]any)
		if len(pair) == 2 {
			if data, ok := pair[1].(map[string]any); ok {
				if _, has := data["err"]; has {
					data["err"] = "<err>"
				}
			}
		}
	}
	gb, _ := json.Marshal(auditJSON(t, got))
	wb, _ := json.Marshal(want)
	return string(gb), string(wb)
}

// assertAudit compares a Go audit trail with the recorded TS one.
func assertAudit(t *testing.T, got Audit, want []any) {
	t.Helper()
	if g, w := auditPair(t, got, want); g != w {
		t.Errorf("audit differs\nGo: %s\nTS: %s", g, w)
	}
}

// assertFiles compares the seven files lists with the TS run's, in order.
func assertFiles(t *testing.T, got, want Files) {
	t.Helper()
	g, _ := json.Marshal(got.listed())
	w, _ := json.Marshal(want.listed())
	if string(g) != string(w) {
		t.Errorf("files lists differ\nGo: %s\nTS: %s", g, w)
	}
}

func assertVol(t *testing.T, mem *MemFS, want map[string]corpusBytes) {
	t.Helper()
	gotS := mem.Vol()

	missing := []string{}
	mismatched := []string{}
	kind := []string{}
	for p, w := range want {
		actual, ok := gotS[p]
		if !ok {
			missing = append(missing, p)
			continue
		}
		// A nil value is a DIRECTORY on both sides: TS's toJSON writes null
		// for an empty one and corpusBytes decodes that to nil, while
		// Vol() reports one as nil. bytes.Equal would call it equal to an
		// empty FILE, so the kinds are compared before the bytes. See #41.
		if (actual == nil) != (w == nil) {
			kind = append(kind, p)
			continue
		}
		if !bytes.Equal(actual, w) {
			mismatched = append(mismatched, p)
		}
	}
	extra := []string{}
	for p := range gotS {
		if _, ok := want[p]; !ok {
			extra = append(extra, p)
		}
	}
	sort.Strings(missing)
	sort.Strings(mismatched)
	sort.Strings(extra)
	sort.Strings(kind)

	if len(missing) > 0 {
		t.Errorf("Go output missing %d paths from TS reference: %v", len(missing), missing)
	}
	if len(extra) > 0 {
		t.Errorf("Go output has %d extra paths not in TS reference: %v", len(extra), extra)
	}
	for _, p := range kind {
		t.Errorf("path %s: one stack has a directory where the other has a "+
			"file (Go nil=%v, TS nil=%v)", p, gotS[p] == nil, want[p] == nil)
	}
	for _, p := range mismatched {
		t.Errorf("path %s: bytes differ\nGo:\n%q\nTS:\n%q\n", p, gotS[p], want[p])
	}
}

// knownParityGaps records scenarios deliberately not mirrored in Go, each
// with the reason. Entries here are exemptions from the
// missing-runner failure in runParityCase and should be rare and
// short-lived. Empty is the healthy state.
var knownParityGaps = map[string]string{}

// phaseShapedCorpora names parity JSON files whose top-level shape is a
// phase replay (label/foo pairs) rather than {opts, prepopulate, vol}.
// They have dedicated test functions and are skipped from the standard
// runner so the parity scenario list shows only single-Generate cases.
var phaseShapedCorpora = map[string]struct{}{
	"merge_retain":        {}, // covered by TestMergeRetainSequence
	"merge_marker_clean":  {}, // covered by TestParityRuns
	"audit_basic":         {}, // covered by TestParityRuns
	"audit_rerun":         {}, // covered by TestParityRuns
	"audit_nested":        {}, // covered by TestParityRuns
	"merge_unresolved":    {}, // covered by TestParityRuns
	"diff_corpus":         {}, // covered by TestDiffCorpusMatchesTS
	"template_corpus":     {}, // covered by TestTemplateCorpusMatchesTS
	"scenario_corpus":     {}, // covered by TestScenarioCorpusMatchesTS
	"copy_exclude_corpus": {}, // covered by TestCopyExcludeCorpusMatchesTS
}

// scenarioMultiPhase holds runners that can't be expressed as a single
// Generate call. Each runner builds the FS state (running multiple
// generations + external edits) and returns the MemFS for assertion.
var scenarioMultiPhase = map[string]func(*testing.T) *MemFS{
	"merge_basic": func(t *testing.T) *MemFS { return mergeRunner(t, "AAA\n", "AAA\nuser-line\n", "BBB\n", "$$body$$") },
	"merge_update": func(t *testing.T) *MemFS {
		return mergeRunner(t, "AAA\n", "// header\nAAA\n// user-comment\n", "BBB\n", "// header\n$$body$$")
	},
	"merge_clean": func(t *testing.T) *MemFS { return mergeRunnerNoEdit(t, "AAA\n", "CCC\n", "$$body$$") },
	"merge_no_baseline": func(t *testing.T) *MemFS {
		// User-authored file is in place but no duplicate baseline
		// exists — typical "first run after adopting jostraca on
		// existing code" state. Merge mode without a baseline falls
		// through to the regular write path (TS FileHandler.ts:282-336
		// leaves the merge block silently when dpath doesn't exist).
		mem := NewMemFS()
		_ = mem.WriteFile("/out/sdk/foo.txt", []byte("USER\n"))
		j := New(WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow }))
		mergeTrue := true
		_, err := j.Generate(Options{
			Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}},
		}, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content("GEN\n") })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
		return mem
	},
	"fragment_subcmp": func(t *testing.T) *MemFS {
		mem := NewMemFS()
		_ = mem.WriteFile("/f01.txt", []byte("TWO-$$a$$-bar-zed-con-foo+<[SLOT]>\n"))
		Foo := func(j *J, arg string) {
			j.Content("FOO[")
			j.Content(arg)
			j.Content("]")
		}
		j := New(WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow }), WithModel(map[string]any{"a": "A"}))
		_, err := j.Generate(Options{}, func(j *J) {
			j.Project(ProjectProps{}, func(j *J) {
				j.File("foo.txt", func(j *J) {
					j.Content("ONE\n")
					j.Fragment(FragmentProps{
						From: "/f01.txt",
						Replace: map[string]any{
							"bar": "BAR",
							"zed": func() string { return "ZED" },
							"con": func(j *J) { j.Content("CON") },
							"foo": func(j *J) { Foo(j, "B") },
						},
					}, func(j *J) {
						j.Content("S")
					})
					j.Content("THREE\n")
				})
			})
		})
		if err != nil {
			t.Fatal(err)
		}
		return mem
	},
}

// mergeRunner runs the canonical 2-phase merge scenario: gen A, user
// edit, regen B with merge mode.
func mergeRunner(t *testing.T, bodyA, userEdit, bodyB, srcTpl string) *MemFS {
	t.Helper()
	mem := NewMemFS()
	now := func() int64 { return frozenNow }
	gen := func(body string, opts Options) {
		j := New(WithFS(mem), WithFolder("/out"), WithNow(now), WithModel(map[string]any{"body": body}))
		_, err := j.Generate(opts, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content(srcTpl) })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	gen(bodyA, Options{})
	_ = mem.WriteFile("/out/sdk/foo.txt", []byte(userEdit))
	mergeTrue := true
	gen(bodyB, Options{Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}}})
	return mem
}

// mergeRunnerNoEdit skips the user edit between generations - exercises
// the clean-merge path where existing matches the prior baseline.
func mergeRunnerNoEdit(t *testing.T, bodyA, bodyB, srcTpl string) *MemFS {
	t.Helper()
	mem := NewMemFS()
	now := func() int64 { return frozenNow }
	gen := func(body string, opts Options) {
		j := New(WithFS(mem), WithFolder("/out"), WithNow(now), WithModel(map[string]any{"body": body}))
		_, err := j.Generate(opts, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content(srcTpl) })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	gen(bodyA, Options{})
	mergeTrue := true
	gen(bodyB, Options{Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}}})
	return mem
}

// parityRuns mirrors the multi-generate scenarios recorded by snapshotRuns
// in tools/extract-parity.js. Each step is an edit (a func over the volume)
// or a generate (options and a root).
type parityStep struct {
	edit func(*MemFS)
	opts Options
	root func(*J)
}

func parityOne(name, body string) func(*J) {
	return func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File(name, func(j *J) { j.Content(body) })
		})
	}
}

func parityAuditTree(a, b string) func(*J) {
	return func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content(a) })
			j.Folder("sub", func(j *J) {
				j.File("b.txt", func(j *J) { j.Content(b) })
			})
		})
	}
}

var parityRuns = map[string][]parityStep{
	"audit_basic": {{root: parityAuditTree("A\n", "B\n")}},
	"audit_rerun": func() []parityStep {
		yes, no := true, false
		return []parityStep{
			{root: parityAuditTree("L1\nL2\nL3\n", "B\n")},
			{edit: func(m *MemFS) { _ = m.WriteFile("/out/app/a.txt", []byte("L1\nU\nL3\n")) }},
			{opts: Options{Existing: Existing{Txt: ExistingTxt{Merge: &yes, Preserve: &yes}}},
				root: parityAuditTree("L1\nG\nL3\n", "B\n")},
			{opts: Options{Existing: Existing{Txt: ExistingTxt{Write: &no, Present: &yes}}},
				root: parityAuditTree("L1\nG2\nL3\n", "B\n")},
			{opts: Options{Existing: Existing{Txt: ExistingTxt{Diff: &yes}}},
				root: parityAuditTree("L1\nG3\nL3\n", "B\n")},
		}
	}(),
	"audit_nested": {
		{edit: func(m *MemFS) {
			_ = m.WriteFile("/src/tree/t.txt", []byte("T $$v$$\n"))
			_ = m.WriteFile("/src/tree/deep/i.png", []byte{0x89, 0x50, 0x00, 0xff})
			_ = m.WriteFile("/src/tree/deep/m.bin", []byte{0x00, 0x01, 0x02})
			_ = m.WriteFile("/out/app/j.txt", []byte("<\n#--START--#\nold\n#--END--#\n>"))
		}},
		{opts: Options{Model: map[string]any{"v": "V"}}, root: func(j *J) {
			j.Project(ProjectProps{Folder: "app"}, func(j *J) {
				j.Folder("x", func(j *J) {
					j.Folder("y", func(j *J) {
						j.File("n.txt", func(j *J) { j.Content("N") })
					})
				})
				j.CopyFiles(CopyFilesProps{From: "/src/tree", To: "c"})
				j.CopyFiles(CopyFilesProps{From: "/src/tree/t.txt", To: "one.txt"})
				j.Inject("j.txt", func(j *J) { j.Content("J") })
			})
		}},
	},
	"merge_marker_clean": func() []parityStep {
		merge := true
		opts := Options{Existing: Existing{Txt: ExistingTxt{Merge: &merge}}}
		doc := func(v string) func(*J) {
			return parityOne("doc.md", "How a conflict looks:\n>>>>>>> EXISTING: "+
				"2020-01-01T00:00:00.000Z/merge\n"+v+"\n")
		}
		return []parityStep{{opts: opts, root: doc("v1")},
			{opts: opts, root: doc("v2")}, {opts: opts, root: doc("v3")}}
	}(),
	"merge_unresolved": func() []parityStep {
		merge := true
		opts := Options{Existing: Existing{Txt: ExistingTxt{Merge: &merge}}}
		return []parityStep{
			{root: parityOne("a.txt", "A\n")},
			{edit: func(m *MemFS) { _ = m.WriteFile("/out/app/a.txt", []byte("A\nuser\n")) }},
			{opts: opts, root: parityOne("a.txt", "A\ngen\n")},
			{opts: opts, root: parityOne("a.txt", "A\ngen2\n")},
		}
	}(),
}

func TestParityRuns(t *testing.T) {
	for name, steps := range parityRuns {
		t.Run(name, func(t *testing.T) {
			body, err := parityFS.ReadFile("testdata/parity/" + name + ".json")
			if err != nil {
				t.Fatal(err)
			}
			var want struct {
				Runs []struct {
					Files Files `json:"files"`
					Audit []any `json:"audit"`
				} `json:"runs"`
				Vol map[string]corpusBytes `json:"vol"`
			}
			if err := json.Unmarshal(body, &want); err != nil {
				t.Fatal(err)
			}
			mem := NewMemFS()
			i := 0
			for _, st := range steps {
				if st.edit != nil {
					st.edit(mem)
					continue
				}
				res, err := New(WithFS(mem), WithFolder("/out"),
					WithNow(func() int64 { return frozenNow })).Generate(st.opts, st.root)
				if err != nil {
					t.Fatal(err)
				}
				if i >= len(want.Runs) {
					t.Fatalf("more generates than TS recorded")
				}
				assertFiles(t, res.Files, want.Runs[i].Files)
				assertAudit(t, res.Audit(), want.Runs[i].Audit)
				i++
			}
			if i != len(want.Runs) {
				t.Fatalf("%d generates, TS recorded %d", i, len(want.Runs))
			}
			assertVol(t, mem, want.Vol)
		})
	}
}
