package jostraca

import (
	"bytes"
	"embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"testing"
)

// corpusBytes is a corpus content value. The format is a JSON string when
// the bytes round-trip through UTF-8, and {"b64": "<base64>"} when they do
// not — see ts/tools/corpus-bytes.js. The corpus is GENERATED by TS and only
// READ here, so TS is the only side that ever decides which form to emit;
// Go only decodes, and so cannot disagree about what "valid UTF-8" means.
type corpusBytes []byte

func (c *corpusBytes) UnmarshalJSON(raw []byte) error {
	raw = bytes.TrimSpace(raw)
	if len(raw) == 0 {
		return fmt.Errorf("empty corpus content value")
	}
	if string(raw) == "null" {
		*c = nil
		return nil
	}
	if raw[0] == '"' {
		var s string
		if err := json.Unmarshal(raw, &s); err != nil {
			return err
		}
		*c = corpusBytes(s)
		return nil
	}
	var obj struct {
		B64 *string `json:"b64"`
	}
	if err := json.Unmarshal(raw, &obj); err != nil {
		return fmt.Errorf("corpus content value is neither a string nor "+
			`{"b64":...}: %s: %w`, raw, err)
	}
	if obj.B64 == nil {
		return fmt.Errorf("corpus content object has no b64 key: %s", raw)
	}
	dec, err := base64.StdEncoding.DecodeString(*obj.B64)
	if err != nil {
		return fmt.Errorf("corpus b64 content: %w", err)
	}
	*c = dec
	return nil
}

//go:embed testdata/parity/*.json
var parityFS embed.FS

// parityCase mirrors the JSON dumped by tools/extract-parity.js. It
// records the TS-side scenario name, options, prepopulated FS state,
// and the expected vol.toJSON() output produced by running the same
// component tree through the TS package.
type parityCase struct {
	Scenario    string                 `json:"scenario"`
	Opts        map[string]any         `json:"opts"`
	Prepopulate map[string]corpusBytes `json:"prepopulate"`
	Vol         map[string]corpusBytes `json:"vol"`
}

// scenarioRunner builds the component tree for a named scenario. The
// runners here mirror the tree shapes in tools/extract-parity.js so a
// byte-equal parity assertion is meaningful.
var scenarioRunners = map[string]func(j *J){
	"quickstart": func(j *J) {
		j.Project(ProjectProps{Folder: "my-app"}, func(j *J) {
			j.Folder("src", func(j *J) {
				j.File("index.js", func(j *J) {
					j.Content("console.log(\"hello world\")\n")
				})
			})
			j.File("package.json", func(j *J) {
				j.Content("{ \"name\": \"my-app\" }\n")
			})
		})
	},
	"template_model": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("config.txt", func(j *J) {
				j.Content("App: $$app.name$$ v$$app.version$$\n")
			})
		})
	},
	"fragment_slot": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("index.html", func(j *J) {
				j.Fragment(FragmentProps{From: "/templates/page.html"}, func(j *J) {
					j.Slot("head", func(j *J) { j.Content("<title>X</title>") })
					j.Slot("body", func(j *J) { j.Content("<h1>Hello</h1>") })
				})
			})
		})
	},
	"inject_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("new content") })
		})
	},
	"copy_file": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/tpl/hello.txt"})
		})
	},
	"list_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.List([]any{"a", "b", "c"}, func(j *J, item any) {
					j.Line(item.(string))
				})
			})
		})
	},
	"line_basic": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.Line("hello")
			})
		})
	},
	"protect": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("cfg.txt", func(j *J) { j.Content("regenerated\n") })
		})
	},
	"unchanged": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("A") })
		})
	},
	"preserve_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"present_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"diff_mode": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"happy_multifile": func(j *J) {
		j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
			j.Folder("js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// custom-foo\n") })
				j.File("bar.js", func(j *J) { j.Content("// custom-bar\n") })
			})
			j.Folder("go", func(j *J) {
				j.File("zed.go", func(j *J) { j.Content("// custom-zed\n") })
			})
		})
	},
	"fragment_nested_in_slot": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("out.txt", func(j *J) {
				j.Fragment(FragmentProps{From: "/f.txt"}, func(j *J) {
					j.Slot("s", func(j *J) {
						j.Fragment(FragmentProps{From: "/f2.txt"}, func(j *J) {})
						j.Content("DIRECT")
					})
				})
			})
		})
	},
	"fragment_relative_from": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Folder("sub", func(j *J) {
				j.File("out.txt", func(j *J) {
					j.Fragment(FragmentProps{From: "frag.txt"}, func(j *J) {})
				})
			})
		})
	},
	"copy_ignore_text": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm"})
		})
	},
	"preserve_and_diff": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"protect_and_present": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File("a.txt", func(j *J) { j.Content("NEW\n") })
		})
	},
	"inject_two_blocks": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"inject_stray_end_marker": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"inject_no_markers": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.Inject("foo.txt", func(j *J) { j.Content("NEW") })
		})
	},
	"no_project_file": func(j *J) {
		j.File("x.txt", func(j *J) { j.Content("hi\n") })
	},
	"dotfile_preserve": func(j *J) {
		j.Project(ProjectProps{Folder: "app"}, func(j *J) {
			j.File(".env", func(j *J) { j.Content("NEW-ENV\n") })
			j.File(".npmrc", func(j *J) { j.Content("NEW-NPMRC\n") })
		})
	},
	"content_empty_folder": func(j *J) {
		j.Folder("", func(j *J) {
			j.File("foo.txt", func(j *J) { j.Content("A") })
		})
	},
	"basic_copy": func(j *J) {
		j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
			j.Folder("js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// custom-foo\n") })
				j.Copy(CopyProps{From: "/tm/bar.txt", To: "bar.txt"})
				j.Copy(CopyProps{From: "/tm/sub"})
			})
		})
	},
	"copy_binary_unlisted_ext": func(j *J) {
		j.Project(ProjectProps{Folder: "p"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm"})
		})
	},
	"existing_bin_classification": func(j *J) {
		j.Project(ProjectProps{Folder: "p"}, func(j *J) {
			j.Copy(CopyProps{From: "/tm/logo.png", To: "logo.png"})
			j.Copy(CopyProps{From: "/tm/mod.wasm", To: "mod.wasm"})
			j.Copy(CopyProps{From: "/tm/readme.txt", To: "readme.txt"})
			j.File("icon.png", func(j *J) { j.Content("NEW-ICON\n") })
		})
	},
	"absolute_paths": func(j *J) {
		// Project.Folder is absolute; Folder name has a leading /.
		// Both must compose into a clean /top/sdk/code/js path even
		// though the global folder option is /top.
		j.Project(ProjectProps{Folder: "/top/sdk"}, func(j *J) {
			j.Folder("/code/js", func(j *J) {
				j.File("foo.js", func(j *J) { j.Content("// foo:0\n") })
			})
		})
	},
}

// scenarioOptions returns per-scenario Options additions; merged on top
// of the WithFS+WithFolder+WithNow base.
func scenarioOptions(scenario string) []Option {
	switch scenario {
	case "template_model":
		return []Option{WithModel(map[string]any{
			"app": map[string]any{"name": "Acme", "version": "1.0.0"},
		})}
	case "copy_file":
		return []Option{WithModel(map[string]any{"name": "World"})}
	case "preserve_mode", "dotfile_preserve":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Preserve: &t}})}
	case "present_mode":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Present: &t}})}
	case "diff_mode":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Diff: &t}})}
	case "preserve_and_diff":
		t := true
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Preserve: &t, Diff: &t}})}
	case "protect_and_present":
		t, f := true, false
		return []Option{WithExisting(Existing{Txt: ExistingTxt{Write: &f, Present: &t}})}
	case "basic_copy":
		return []Option{WithModel(map[string]any{"x": map[string]any{"y": "Y", "z": "Z"}})}
	case "copy_ignore_text", "copy_binary_unlisted_ext":
		return []Option{WithModel(map[string]any{"v": "V"})}
	case "existing_bin_classification":
		t := true
		return []Option{
			WithModel(map[string]any{"v": "V"}),
			WithExisting(Existing{
				Txt: ExistingTxt{Diff: &t},
				Bin: ExistingBin{Preserve: &t},
			}),
		}
	case "absolute_paths":
		return []Option{WithFolder("/top")}
	}
	return nil
}

const frozenNow int64 = 1735689600000

func TestParityScenarios(t *testing.T) {
	entries, err := parityFS.ReadDir("testdata/parity")
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".json")
		// Phase-shaped corpora are owned by their dedicated test functions
		// (e.g. merge_retain.json drives TestMergeRetainSequence). They
		// don't fit the {opts, prepopulate, vol} runner shape.
		if _, isPhaseShaped := phaseShapedCorpora[name]; isPhaseShaped {
			continue
		}
		t.Run(name, func(t *testing.T) {
			runParityCase(t, "testdata/parity/"+e.Name(), name)
		})
	}
}

func runParityCase(t *testing.T, path, name string) {
	t.Helper()
	body, err := parityFS.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var c parityCase
	if err := json.Unmarshal(body, &c); err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}

	// Multi-phase scenarios live in scenarioMultiPhase and own their
	// own MemFS lifecycle.
	if mp, ok := scenarioMultiPhase[name]; ok {
		mem := mp(t)
		assertVol(t, mem, c.Vol)
		return
	}

	runner, ok := scenarioRunners[name]
	if !ok {
		if reason, known := knownParityGaps[name]; known {
			t.Skipf("known parity gap: %s", reason)
			return
		}
		// A missing runner is a parity gap, not a non-event: the TS side has
		// a scenario the Go port does not answer for. Fail loudly, and use
		// knownParityGaps to carry a deliberate, documented exemption.
		t.Fatalf("scenario %s has no Go runner; add one to scenarioRunners "+
			"(or record a deliberate exemption in knownParityGaps)", name)
		return
	}

	mem := NewMemFS()
	for k, v := range c.Prepopulate {
		_ = mem.WriteFile(k, []byte(v))
	}

	opts := []Option{WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow })}
	opts = append(opts, scenarioOptions(name)...)
	j := New(opts...)

	if _, err := j.Generate(Options{}, runner); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	assertVol(t, mem, c.Vol)
}

func assertVol(t *testing.T, mem *MemFS, want map[string]corpusBytes) {
	t.Helper()
	gotS := mem.Vol()

	missing := []string{}
	mismatched := []string{}
	for p, w := range want {
		actual, ok := gotS[p]
		if !ok {
			missing = append(missing, p)
			continue
		}
		if !bytes.Equal(actual, w) {
			mismatched = append(mismatched, p)
		}
	}
	extra := []string{}
	for p := range gotS {
		if _, ok := want[p]; !ok {
			extra = append(extra, p)
		}
	}
	sort.Strings(missing)
	sort.Strings(mismatched)
	sort.Strings(extra)

	if len(missing) > 0 {
		t.Errorf("Go output missing %d paths from TS reference: %v", len(missing), missing)
	}
	if len(extra) > 0 {
		t.Errorf("Go output has %d extra paths not in TS reference: %v", len(extra), extra)
	}
	for _, p := range mismatched {
		t.Errorf("path %s: bytes differ\nGo:\n%q\nTS:\n%q\n", p, gotS[p], want[p])
	}
}

// knownParityGaps records scenarios deliberately not mirrored in Go, each
// with the reason. Entries here are exemptions from the
// missing-runner failure in runParityCase and should be rare and
// short-lived. Empty is the healthy state.
var knownParityGaps = map[string]string{}

// phaseShapedCorpora names parity JSON files whose top-level shape is a
// phase replay (label/foo pairs) rather than {opts, prepopulate, vol}.
// They have dedicated test functions and are skipped from the standard
// runner so the parity scenario list shows only single-Generate cases.
var phaseShapedCorpora = map[string]struct{}{
	"merge_retain":        {}, // covered by TestMergeRetainSequence
	"diff_corpus":         {}, // covered by TestDiffCorpusMatchesTS
	"template_corpus":     {}, // covered by TestTemplateCorpusMatchesTS
	"scenario_corpus":     {}, // covered by TestScenarioCorpusMatchesTS
	"copy_exclude_corpus": {}, // covered by TestCopyExcludeCorpusMatchesTS
}

// scenarioMultiPhase holds runners that can't be expressed as a single
// Generate call. Each runner builds the FS state (running multiple
// generations + external edits) and returns the MemFS for assertion.
var scenarioMultiPhase = map[string]func(*testing.T) *MemFS{
	"merge_basic": func(t *testing.T) *MemFS { return mergeRunner(t, "AAA\n", "AAA\nuser-line\n", "BBB\n", "$$body$$") },
	"merge_update": func(t *testing.T) *MemFS {
		return mergeRunner(t, "AAA\n", "// header\nAAA\n// user-comment\n", "BBB\n", "// header\n$$body$$")
	},
	"merge_clean": func(t *testing.T) *MemFS { return mergeRunnerNoEdit(t, "AAA\n", "CCC\n", "$$body$$") },
	"merge_no_baseline": func(t *testing.T) *MemFS {
		// User-authored file is in place but no duplicate baseline
		// exists — typical "first run after adopting jostraca on
		// existing code" state. Merge mode without a baseline falls
		// through to the regular write path (TS FileHandler.ts:282-336
		// leaves the merge block silently when dpath doesn't exist).
		mem := NewMemFS()
		_ = mem.WriteFile("/out/sdk/foo.txt", []byte("USER\n"))
		j := New(WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow }))
		mergeTrue := true
		_, err := j.Generate(Options{
			Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}},
		}, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content("GEN\n") })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
		return mem
	},
	"fragment_subcmp": func(t *testing.T) *MemFS {
		mem := NewMemFS()
		_ = mem.WriteFile("/f01.txt", []byte("TWO-$$a$$-bar-zed-con-foo+<[SLOT]>\n"))
		Foo := func(j *J, arg string) {
			j.Content("FOO[")
			j.Content(arg)
			j.Content("]")
		}
		j := New(WithFS(mem), WithFolder("/out"), WithNow(func() int64 { return frozenNow }), WithModel(map[string]any{"a": "A"}))
		_, err := j.Generate(Options{}, func(j *J) {
			j.Project(ProjectProps{}, func(j *J) {
				j.File("foo.txt", func(j *J) {
					j.Content("ONE\n")
					j.Fragment(FragmentProps{
						From: "/f01.txt",
						Replace: map[string]any{
							"bar": "BAR",
							"zed": func() string { return "ZED" },
							"con": func(j *J) { j.Content("CON") },
							"foo": func(j *J) { Foo(j, "B") },
						},
					}, func(j *J) {
						j.Content("S")
					})
					j.Content("THREE\n")
				})
			})
		})
		if err != nil {
			t.Fatal(err)
		}
		return mem
	},
}

// mergeRunner runs the canonical 2-phase merge scenario: gen A, user
// edit, regen B with merge mode.
func mergeRunner(t *testing.T, bodyA, userEdit, bodyB, srcTpl string) *MemFS {
	t.Helper()
	mem := NewMemFS()
	now := func() int64 { return frozenNow }
	gen := func(body string, opts Options) {
		j := New(WithFS(mem), WithFolder("/out"), WithNow(now), WithModel(map[string]any{"body": body}))
		_, err := j.Generate(opts, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content(srcTpl) })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	gen(bodyA, Options{})
	_ = mem.WriteFile("/out/sdk/foo.txt", []byte(userEdit))
	mergeTrue := true
	gen(bodyB, Options{Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}}})
	return mem
}

// mergeRunnerNoEdit skips the user edit between generations - exercises
// the clean-merge path where existing matches the prior baseline.
func mergeRunnerNoEdit(t *testing.T, bodyA, bodyB, srcTpl string) *MemFS {
	t.Helper()
	mem := NewMemFS()
	now := func() int64 { return frozenNow }
	gen := func(body string, opts Options) {
		j := New(WithFS(mem), WithFolder("/out"), WithNow(now), WithModel(map[string]any{"body": body}))
		_, err := j.Generate(opts, func(j *J) {
			j.Project(ProjectProps{Folder: "sdk"}, func(j *J) {
				j.File("foo.txt", func(j *J) { j.Content(srcTpl) })
			})
		})
		if err != nil {
			t.Fatal(err)
		}
	}
	gen(bodyA, Options{})
	mergeTrue := true
	gen(bodyB, Options{Existing: Existing{Txt: ExistingTxt{Merge: &mergeTrue}}})
	return mem
}
