package jostraca

import (
	"encoding/json"
	"sort"
	"strings"
	"testing"
)

// Cross-stack differential test for the OPTION SURFACE.
//
// testdata/parity/scenario_corpus.json is generated by
// ts/tools/scenario-corpus.js and records TS's exact output tree for every
// combination of output folder, existing-file mode, on-disk state and
// filename shape. This replays them through Go and asserts byte equality.
//
// Why this exists: every defect review found on this branch — thirteen of
// them — needed a DEFAULT, a DEGENERATE VALUE, or an OPTION COMBINATION to
// reach, not unusual content. The diff and template corpora vary content
// exhaustively while holding options at typical values, so none of those
// defects were reachable from either. This corpus does the opposite:
// modest content, exhaustive options.
//
// If it fails, the two stacks have drifted on option handling. Do not
// regenerate the corpus to make it pass — that records the drift as
// expected. Find which side changed.

// scenarioCorpusFileSpec describes one output file: how it is produced and
// what goes into it. Only the binary-classification block carries these —
// the text block is fully described by Names + Seed, and keeps the exact
// JSON shape it had before that block existed.
type scenarioCorpusFileSpec struct {
	Name string       `json:"name"`
	Kind string       `json:"kind"` // "file" (File+Content) or "copy" (Copy)
	Body corpusBytes  `json:"body"`
	Seed *corpusBytes `json:"seed"`
}

type scenarioCorpusCase struct {
	Name     string                   `json:"name"`
	Folder   *string                  `json:"folder"`
	Existing map[string]any           `json:"existing"`
	Seed     *string                  `json:"seed"`
	Baseline *string                  `json:"baseline"`
	Names    []string                 `json:"names"`
	Files    []scenarioCorpusFileSpec `json:"files"`
	Sources  map[string]corpusBytes   `json:"sources"`
	Vol      map[string]corpusBytes   `json:"vol"`
	Error    bool                     `json:"error"`
}

type scenarioCorpusFile struct {
	Scenario string               `json:"scenario"`
	Cases    []scenarioCorpusCase `json:"cases"`
}

// existingFromCorpus converts the corpus's JSON shape into the Go Existing
// struct. Kept explicit rather than routed through OptionsFromMap so a
// change in that decoder cannot silently alter what this test exercises.
//
// `bin` has no diff and no merge — the TS shape validator rejects both
// (`the property "diff" is not allowed`) and ExistingBin has no such field
// — so the corpus never carries them and nothing here decodes them.
func existingFromCorpus(t *testing.T, raw map[string]any) Existing {
	t.Helper()
	var ex Existing
	if raw == nil {
		return ex
	}
	boolp := func(m map[string]any, k string) *bool {
		v, ok := m[k].(bool)
		if !ok {
			return nil
		}
		return &v
	}
	if txt, _ := raw["txt"].(map[string]any); txt != nil {
		ex.Txt = ExistingTxt{
			Write:    boolp(txt, "write"),
			Preserve: boolp(txt, "preserve"),
			Present:  boolp(txt, "present"),
			Diff:     boolp(txt, "diff"),
			Merge:    boolp(txt, "merge"),
		}
	}
	if bin, _ := raw["bin"].(map[string]any); bin != nil {
		ex.Bin = ExistingBin{
			Write:    boolp(bin, "write"),
			Preserve: boolp(bin, "preserve"),
			Present:  boolp(bin, "present"),
		}
	}
	return ex
}

// filesOf normalises a case to the per-file spec form. A case from the text
// block carries only Names + Seed, which says the same thing shorter.
func filesOf(c scenarioCorpusCase) []scenarioCorpusFileSpec {
	if c.Files != nil {
		return c.Files
	}
	out := make([]scenarioCorpusFileSpec, 0, len(c.Names))
	for _, name := range c.Names {
		spec := scenarioCorpusFileSpec{
			Name: name,
			Kind: "file",
			Body: corpusBytes("GENERATED\n"),
		}
		if c.Seed != nil {
			sb := corpusBytes(*c.Seed)
			spec.Seed = &sb
		}
		out = append(out, spec)
	}
	return out
}

// scenarioSrcDir mirrors SRCDIR in ts/tools/scenario-corpus.js.
const scenarioSrcDir = "/src"

func TestScenarioCorpusMatchesTS(t *testing.T) {
	body, err := parityFS.ReadFile("testdata/parity/scenario_corpus.json")
	if err != nil {
		t.Fatal(err)
	}

	var corpus scenarioCorpusFile
	if err := json.Unmarshal(body, &corpus); err != nil {
		t.Fatalf("decode scenario_corpus.json: %v", err)
	}
	if len(corpus.Cases) < 1100 {
		t.Fatalf("corpus looks truncated: %d cases", len(corpus.Cases))
	}

	mismatch, errmismatch := 0, 0

	for _, c := range corpus.Cases {
		mem := NewMemFS()

		// A relative folder is passed through exactly as recorded — that is
		// the point of the axis. TS strips memfs's process.cwd() prefix
		// when generating, so the recorded keys are already relative and
		// line up with what Go's MemFS (which has no cwd) produces.
		folder := "."
		if c.Folder != nil {
			folder = *c.Folder
		}

		// Seed paths mirror the generator: relative to the folder, with a
		// bare `.` contributing no segment.
		prefix := strings.TrimSuffix(strings.TrimPrefix(folder, "./"), "/")
		if prefix == "." {
			prefix = ""
		}
		join := func(rest string) string {
			if prefix == "" {
				return rest
			}
			return prefix + "/" + rest
		}

		files := filesOf(c)

		// Copy sources sit outside every output folder, at an absolute
		// path, so they are identical for every folder setting.
		srcs := make([]string, 0, len(c.Sources))
		for p := range c.Sources {
			srcs = append(srcs, p)
		}
		sort.Strings(srcs)
		for _, p := range srcs {
			if err := mem.WriteFile(p, c.Sources[p]); err != nil {
				t.Fatal(err)
			}
		}

		for _, f := range files {
			if f.Seed == nil {
				continue
			}
			if err := mem.WriteFile(join(f.Name), *f.Seed); err != nil {
				t.Fatal(err)
			}
		}
		if c.Baseline != nil {
			for _, f := range files {
				p := join(".jostraca/generated/" + f.Name)
				if err := mem.WriteFile(p, []byte(*c.Baseline)); err != nil {
					t.Fatal(err)
				}
			}
		}

		opts := []Option{WithFS(mem), WithNow(func() int64 { return 1735689600000 })}
		if c.Folder != nil {
			opts = append(opts, WithFolder(*c.Folder))
		}
		j := New(opts...)

		_, gerr := j.Generate(Options{
			Existing: existingFromCorpus(t, c.Existing),
			// Matches MODEL in ts/tools/scenario-corpus.js. Only the binary
			// payloads carry a `$$v$$` marker, where substituting it is the
			// visible symptom of the file having been treated as text.
			Model: map[string]any{"v": "V"},
		}, func(j *J) {
			j.Folder("", func(j *J) {
				for _, f := range files {
					f := f
					at := strings.LastIndex(f.Name, "/")
					base := f.Name
					if at >= 0 {
						base = f.Name[at+1:]
					}
					emit := func(j *J) {
						if f.Kind == "copy" {
							j.Copy(CopyProps{
								From: scenarioSrcDir + "/" + base,
								To:   base,
							})
							return
						}
						j.File(base, func(j *J) { j.Content(string(f.Body)) })
					}
					if at < 0 {
						emit(j)
						continue
					}
					j.Folder(f.Name[:at], emit)
				}
			})
		})

		if c.Error {
			if gerr == nil {
				errmismatch++
				if errmismatch <= 10 {
					t.Errorf("%s: TS failed but Go succeeded", c.Name)
				}
				continue
			}
			// Both threw. Fall through to the tree comparison rather than
			// calling it a match here: a failed build still leaves whatever
			// it wrote before it stopped, and two stacks that throw at
			// DIFFERENT points leave different partial trees. Skipping the
			// comparison bought an assertion that both sides failed and
			// nothing about what they left behind. See docs/design/PARITY_PLAN.md 2.1.
		} else if gerr != nil {
			errmismatch++
			if errmismatch <= 10 {
				t.Errorf("%s: TS succeeded but Go failed: %v", c.Name, gerr)
			}
			continue
		}

		// Go strings are byte-transparent, so flattening both sides to
		// map[string]string is lossless even for the binary cases — and it
		// keeps sameTree/showTree at the signatures the other corpora in
		// this package share.
		got := map[string]string{}
		for k, v := range mem.Vol() {
			got[k] = string(v)
		}
		want := map[string]string{}
		for k, v := range c.Vol {
			want[k] = string(v)
		}

		if !sameTree(got, want) {
			mismatch++
			if mismatch <= 12 {
				t.Errorf("%s: output tree differs\n go=%s\n ts=%s",
					c.Name, showTree(got), showTree(want))
			}
		}
	}

	if mismatch > 0 || errmismatch > 0 {
		t.Errorf("option-surface handling differs on %d/%d cases (+%d error mismatches)",
			mismatch, len(corpus.Cases), errmismatch)
	}
}

func sameTree(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, av := range a {
		bv, ok := b[k]
		if !ok || av != bv {
			return false
		}
	}
	return true
}

func showTree(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var sb strings.Builder
	for _, k := range keys {
		sb.WriteString("\n   " + k + " = ")
		v := m[k]
		if len(v) > 90 {
			v = v[:90] + "..."
		}
		sb.WriteString(strings.ReplaceAll(v, "\n", "\\n"))
	}
	return sb.String()
}
