package jostraca

import (
	"encoding/json"
	"sort"
	"strings"
	"testing"
)

// Cross-stack differential test for the OPTION SURFACE.
//
// testdata/parity/scenario_corpus.json is generated by
// ts/tools/scenario-corpus.js and records TS's exact output tree for every
// combination of output folder, existing-file mode, on-disk state and
// filename shape. This replays them through Go and asserts byte equality.
//
// Why this exists: every defect review found on this branch — thirteen of
// them — needed a DEFAULT, a DEGENERATE VALUE, or an OPTION COMBINATION to
// reach, not unusual content. The diff and template corpora vary content
// exhaustively while holding options at typical values, so none of those
// defects were reachable from either. This corpus does the opposite:
// modest content, exhaustive options.
//
// If it fails, the two stacks have drifted on option handling. Do not
// regenerate the corpus to make it pass — that records the drift as
// expected. Find which side changed.

type scenarioCorpusCase struct {
	Name     string            `json:"name"`
	Folder   *string           `json:"folder"`
	Existing map[string]any    `json:"existing"`
	Seed     *string           `json:"seed"`
	Baseline *string           `json:"baseline"`
	Names    []string          `json:"names"`
	Vol      map[string]string `json:"vol"`
	Error    bool              `json:"error"`
}

type scenarioCorpusFile struct {
	Scenario string               `json:"scenario"`
	Cases    []scenarioCorpusCase `json:"cases"`
}

// existingFromMap converts the corpus's JSON shape into the Go Existing
// struct. Kept explicit rather than routed through OptionsFromMap so a
// change in that decoder cannot silently alter what this test exercises.
func existingFromCorpus(t *testing.T, raw map[string]any) Existing {
	t.Helper()
	var ex Existing
	if raw == nil {
		return ex
	}
	txt, _ := raw["txt"].(map[string]any)
	if txt == nil {
		return ex
	}
	boolp := func(k string) *bool {
		v, ok := txt[k].(bool)
		if !ok {
			return nil
		}
		return &v
	}
	ex.Txt = ExistingTxt{
		Write:    boolp("write"),
		Preserve: boolp("preserve"),
		Present:  boolp("present"),
		Diff:     boolp("diff"),
		Merge:    boolp("merge"),
	}
	return ex
}

func TestScenarioCorpusMatchesTS(t *testing.T) {
	body, err := parityFS.ReadFile("testdata/parity/scenario_corpus.json")
	if err != nil {
		t.Fatal(err)
	}

	var corpus scenarioCorpusFile
	if err := json.Unmarshal(body, &corpus); err != nil {
		t.Fatalf("decode scenario_corpus.json: %v", err)
	}
	if len(corpus.Cases) < 400 {
		t.Fatalf("corpus looks truncated: %d cases", len(corpus.Cases))
	}

	mismatch, errmismatch := 0, 0

	for _, c := range corpus.Cases {
		mem := NewMemFS()

		// A relative folder is passed through exactly as recorded — that is
		// the point of the axis. TS strips memfs's process.cwd() prefix
		// when generating, so the recorded keys are already relative and
		// line up with what Go's MemFS (which has no cwd) produces.
		folder := "."
		if c.Folder != nil {
			folder = *c.Folder
		}

		// Seed paths mirror the generator: relative to the folder, with a
		// bare `.` contributing no segment.
		prefix := strings.TrimSuffix(strings.TrimPrefix(folder, "./"), "/")
		if prefix == "." {
			prefix = ""
		}
		join := func(rest string) string {
			if prefix == "" {
				return rest
			}
			return prefix + "/" + rest
		}

		if c.Seed != nil {
			for _, name := range c.Names {
				if err := mem.WriteFile(join(name), []byte(*c.Seed)); err != nil {
					t.Fatal(err)
				}
			}
		}
		if c.Baseline != nil {
			for _, name := range c.Names {
				p := join(".jostraca/generated/" + name)
				if err := mem.WriteFile(p, []byte(*c.Baseline)); err != nil {
					t.Fatal(err)
				}
			}
		}

		opts := []Option{WithFS(mem), WithNow(func() int64 { return 1735689600000 })}
		if c.Folder != nil {
			opts = append(opts, WithFolder(*c.Folder))
		}
		j := New(opts...)

		_, gerr := j.Generate(Options{Existing: existingFromCorpus(t, c.Existing)},
			func(j *J) {
				j.Folder("", func(j *J) {
					for _, name := range c.Names {
						at := strings.LastIndex(name, "/")
						if at < 0 {
							n := name
							j.File(n, func(j *J) { j.Content("GENERATED\n") })
							continue
						}
						dir, base := name[:at], name[at+1:]
						j.Folder(dir, func(j *J) {
							j.File(base, func(j *J) { j.Content("GENERATED\n") })
						})
					}
				})
			})

		if c.Error {
			if gerr == nil {
				errmismatch++
				if errmismatch <= 10 {
					t.Errorf("%s: TS failed but Go succeeded", c.Name)
				}
			}
			continue
		}
		if gerr != nil {
			errmismatch++
			if errmismatch <= 10 {
				t.Errorf("%s: TS succeeded but Go failed: %v", c.Name, gerr)
			}
			continue
		}

		got := map[string]string{}
		for k, v := range mem.Vol() {
			got[k] = string(v)
		}

		if !sameTree(got, c.Vol) {
			mismatch++
			if mismatch <= 12 {
				t.Errorf("%s: output tree differs\n go=%s\n ts=%s",
					c.Name, showTree(got), showTree(c.Vol))
			}
		}
	}

	if mismatch > 0 || errmismatch > 0 {
		t.Errorf("option-surface handling differs on %d/%d cases (+%d error mismatches)",
			mismatch, len(corpus.Cases), errmismatch)
	}
}

func sameTree(a, b map[string]string) bool {
	if len(a) != len(b) {
		return false
	}
	for k, av := range a {
		bv, ok := b[k]
		if !ok || av != bv {
			return false
		}
	}
	return true
}

func showTree(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var sb strings.Builder
	for _, k := range keys {
		sb.WriteString("\n   " + k + " = ")
		v := m[k]
		if len(v) > 90 {
			v = v[:90] + "..."
		}
		sb.WriteString(strings.ReplaceAll(v, "\n", "\\n"))
	}
	return sb.String()
}
