package jostraca

import (
	"encoding/json"
	"strings"
	"testing"
)

// Cross-stack differential test for the template engine.
//
// testdata/parity/template_corpus.json is generated by
// ts/tools/template-corpus.js and records TS's exact output — or its exact
// failure — for every case. This replays them through the Go engine and
// asserts byte equality.
//
// Why this exists: the template engine is the other place where two
// independent implementations have to agree (go/template.go is 746 lines;
// the TS engine lives in src/util/basic.ts). Its previous "parity" test,
// template_corpus_test.go, is a set of Go expectations hand-transcribed
// from the TS test file — it only covers the cases someone thought to
// write, and nothing checks it still matches TS. That is precisely the
// setup that let the merge engines disagree on ~72% of non-trivial inputs
// while every test passed.
//
// If this fails, the two engines have drifted. Do not "fix" it by
// regenerating the corpus — that records the drift as expected. Find which
// side changed.

type templateCorpusSpec struct {
	Open    string         `json:"open"`
	Close   string         `json:"close"`
	Ref     string         `json:"ref"`
	Replace map[string]any `json:"replace"`
	Eject   []any          `json:"eject"`
}

type templateCorpusCase struct {
	Name  string             `json:"name"`
	Src   string             `json:"src"`
	Model any                `json:"model"`
	Spec  templateCorpusSpec `json:"spec"`
	Out   string             `json:"out"`
	Error bool               `json:"error"`
}

type templateCorpusFile struct {
	Scenario string               `json:"scenario"`
	Cases    []templateCorpusCase `json:"cases"`
}

// corpusReplaceFuncs mirrors FNS in ts/tools/template-corpus.js. JSON
// cannot carry a closure, so a function-valued replace is encoded as
// {"$fn": "<name>"} and both stacks implement the same fixed set by name.
// This is what gets the function-valued replace path under differential
// test.
var corpusReplaceFuncs = map[string]func(map[string]string, string) string{
	"upper": func(_ map[string]string, match string) string {
		return strings.ToUpper(match)
	},
	"lower": func(_ map[string]string, match string) string {
		return strings.ToLower(match)
	},
	"fixed": func(_ map[string]string, _ string) string {
		return "FIXED"
	},
	"wrap": func(_ map[string]string, match string) string {
		return "[" + match + "]"
	},
}

func hydrateCorpusReplace(t *testing.T, raw map[string]any) map[string]any {
	t.Helper()
	if raw == nil {
		return nil
	}
	out := make(map[string]any, len(raw))
	for k, v := range raw {
		if m, ok := v.(map[string]any); ok {
			name, _ := m["$fn"].(string)
			fn, known := corpusReplaceFuncs[name]
			if !known {
				t.Fatalf("case uses unknown replace function %q", name)
			}
			out[k] = ReplaceFunc(fn)
			continue
		}
		out[k] = v
	}
	return out
}

func TestTemplateCorpusMatchesTS(t *testing.T) {
	body, err := parityFS.ReadFile("testdata/parity/template_corpus.json")
	if err != nil {
		t.Fatal(err)
	}

	var corpus templateCorpusFile
	if err := json.Unmarshal(body, &corpus); err != nil {
		t.Fatalf("decode template_corpus.json: %v", err)
	}
	if len(corpus.Cases) < 200 {
		t.Fatalf("corpus looks truncated: %d cases", len(corpus.Cases))
	}

	mismatch, errmismatch := 0, 0

	for _, c := range corpus.Cases {
		spec := &TemplateSpec{
			Open:    c.Spec.Open,
			Close:   c.Spec.Close,
			Ref:     c.Spec.Ref,
			Replace: hydrateCorpusReplace(t, c.Spec.Replace),
		}
		if len(c.Spec.Eject) == 2 {
			spec.Eject = c.Spec.Eject
		}

		got, gerr := Template(c.Src, c.Model, spec)

		if c.Error {
			if gerr == nil {
				errmismatch++
				t.Errorf("%s: TS failed but Go succeeded\n src=%q\n go=%q",
					c.Name, c.Src, got)
			}
			continue
		}

		if gerr != nil {
			errmismatch++
			if errmismatch <= 10 {
				t.Errorf("%s: TS succeeded but Go failed\n src=%q\n ts=%q\n err=%v",
					c.Name, c.Src, c.Out, gerr)
			}
			continue
		}

		if got != c.Out {
			mismatch++
			if mismatch <= 15 {
				t.Errorf("%s: output differs\n src=%q\n spec=%+v\n go=%q\n ts=%q",
					c.Name, c.Src, c.Spec, got, c.Out)
			}
		}
	}

	if mismatch > 0 || errmismatch > 0 {
		t.Errorf("template engines disagree on %d/%d cases (+%d error mismatches)",
			mismatch, len(corpus.Cases), errmismatch)
	}
}
