package jostraca

import (
	"encoding/json"
	"strings"
	"testing"
)

// THE BRIDGE (tree.go, twin of ts/src/tree.ts): a component tree given
// as plain decoded JSON, generated by the same components a
// hand-written generator calls.

func treeGen(t *testing.T, src string) map[string][]byte {
	t.Helper()
	var tree any
	if err := json.Unmarshal([]byte(src), &tree); err != nil {
		t.Fatal(err)
	}
	root, err := CmpTree(tree)
	if err != nil {
		t.Fatal(err)
	}
	res, err := New(WithMem(), WithFolder("/top"),
		WithNow(func() int64 { return 1 })).Generate(Options{}, root)
	if err != nil {
		t.Fatal(err)
	}
	return res.Vol()
}

func TestCmpTreeGeneratesFiles(t *testing.T) {
	vol := treeGen(t, `{
	  "cmp": "Folder", "props": {"name": "src"},
	  "children": [{
	    "cmp": "File", "props": {"name": "planet.ts"},
	    "children": [
	      {"cmp": "Content", "props": {"src": "export interface Planet {\n"}},
	      {"cmp": "Content", "props": {"src": "  id: string\n"}},
	      {"cmp": "Content", "props": {"src": "}\n"}}
	    ]
	  }]
	}`)

	got := string(vol["/top/src/planet.ts"])
	want := "export interface Planet {\n  id: string\n}\n"
	if got != want {
		t.Fatalf("planet.ts: %q", got)
	}
}

// A list root becomes siblings.
func TestCmpTreeSiblingRoots(t *testing.T) {
	vol := treeGen(t, `[
	  {"cmp":"File","props":{"name":"a.txt"},
	   "children":[{"cmp":"Content","props":{"src":"A"}}]},
	  {"cmp":"File","props":{"name":"b.txt"},
	   "children":[{"cmp":"Content","props":{"src":"B"}}]}
	]`)

	if string(vol["/top/a.txt"]) != "A" || string(vol["/top/b.txt"]) != "B" {
		t.Fatalf("siblings: %q %q", vol["/top/a.txt"], vol["/top/b.txt"])
	}
}

// THE PER-ITEM BINDINGS REACH THE CHILDREN. A hand-written body takes
// them as its parameter; a data child has none, so the thunk merges
// them under its own props.
func TestCmpTreeListItemsReachTheirChildren(t *testing.T) {
	vol := treeGen(t, `{
	  "cmp":"File","props":{"name":"l.txt"},
	  "children":[{
	    "cmp":"ListItems","props":{"item":[{"n":1},{"n":2}]},
	    "children":[{"cmp":"Content","props":{"src":"n={item.n}\n"}}]
	  }]
	}`)

	if got := string(vol["/top/l.txt"]); got != "n=1\nn=2\n\n" {
		t.Fatalf("list: %q", got)
	}
}

// A `Line` renders like a `Content`, which is what lets it carry the
// per-item bindings too. The TypeScript side had to be corrected to
// match this port.
func TestCmpTreeListItemsWithLine(t *testing.T) {
	vol := treeGen(t, `{
	  "cmp":"File","props":{"name":"l.txt"},
	  "children":[{
	    "cmp":"ListItems","props":{"item":[{"n":1},{"n":2}],"line":false},
	    "children":[{"cmp":"Line","props":{"src":"n={item.n}"}}]
	  }]
	}`)

	if got := string(vol["/top/l.txt"]); got != "n=1\nn=2\n" {
		t.Fatalf("list+line: %q", got)
	}
}

// THE NAMES TWO COMPONENTS SHIPPED UNDER still resolve.
func TestCmpTreeDeprecatedNames(t *testing.T) {
	if treeCmpDeprecated["Copy"] != "CopyFiles" ||
		treeCmpDeprecated["List"] != "ListItems" {
		t.Fatal("deprecated map")
	}

	vol := treeGen(t, `{
	  "cmp":"File","props":{"name":"l.txt"},
	  "children":[{
	    "cmp":"List","props":{"item":[{"n":1}],"line":false},
	    "children":[{"cmp":"Content","props":{"src":"n={item.n}\n"}}]
	  }]
	}`)

	if got := string(vol["/top/l.txt"]); got != "n=1\n" {
		t.Fatalf("deprecated List: %q", got)
	}
}

// THE TREE MAY NOT CHOOSE THE OUTPUT ROOT. ProjectOp takes `folder` as
// given, which is right when a developer wrote the call and wrong when
// the tree is input.
func TestCmpTreeCannotEscapeTheOutputFolder(t *testing.T) {
	bad := func(src string) string {
		var tree any
		if err := json.Unmarshal([]byte(src), &tree); err != nil {
			t.Fatal(err)
		}
		_, err := CmpTree(tree)
		if err == nil {
			return ""
		}
		return err.Error()
	}

	if msg := bad(`{"cmp":"Project","props":{"folder":"/escaped"}}`); !strings.Contains(
		msg, "must not be absolute") {
		t.Fatalf("absolute: %q", msg)
	}
	if msg := bad(`{"cmp":"Project","props":{"folder":"../../escaped"}}`); !strings.Contains(
		msg, `".." segment`) {
		t.Fatalf("upward: %q", msg)
	}
	if msg := bad(`{"cmp":"Project","props":{"folder":1}}`); !strings.Contains(
		msg, "folder is not a string") {
		t.Fatalf("non-string: %q", msg)
	}

	// A folder BELOW the root is what the prop is for.
	vol := treeGen(t, `{
	  "cmp":"Project","props":{"folder":"sdk"},
	  "children":[{"cmp":"File","props":{"name":"x.txt"},
	    "children":[{"cmp":"Content","props":{"src":"a"}}]}]
	}`)
	if string(vol["/top/sdk/x.txt"]) != "a" {
		t.Fatalf("sdk: %q", vol["/top/sdk/x.txt"])
	}
}

// A malformed tree is refused by the call that reads it, naming the
// offending node by path.
func TestCmpTreeMalformed(t *testing.T) {
	cases := []struct{ src, want string }{
		{`"File"`, "node is not an object"},
		{`{}`, "node has no cmp name"},
		{`{"cmp":""}`, "node has no cmp name"},
		{`{"cmp":"Nope"}`, "unknown component: Nope"},
		{`{"cmp":"File","props":[]}`, "props is not an object"},
		{`{"cmp":"File","children":{}}`, "children is not an array"},
		{`{"cmp":"Folder","children":[{"cmp":"File","children":[{}]}]}`,
			"(at [0]/Folder[0]/File[0])"},
	}
	for _, c := range cases {
		var tree any
		if err := json.Unmarshal([]byte(c.src), &tree); err != nil {
			t.Fatal(err)
		}
		_, err := CmpTree(tree)
		if err == nil || !strings.Contains(err.Error(), c.want) {
			t.Fatalf("%s -> %v, want %q", c.src, err, c.want)
		}
	}
}

// A caller may add their own component, or override one.
func TestCmpTreeCustomComponents(t *testing.T) {
	var tree any
	if err := json.Unmarshal([]byte(`{
	  "cmp":"File","props":{"name":"x.txt"},
	  "children":[{"cmp":"Twice","props":{"src":"ab"}}]
	}`), &tree); err != nil {
		t.Fatal(err)
	}

	root, err := CmpTree(tree, CmpTreeOptions{Cmp: map[string]CmpTreeCmp{
		"Twice": func(j *J, p map[string]any, _ []func(*J)) {
			s, _ := p["src"].(string)
			j.Content(s + s)
		},
	}})
	if err != nil {
		t.Fatal(err)
	}

	res, err := New(WithMem(), WithFolder("/top"),
		WithNow(func() int64 { return 1 })).Generate(Options{}, root)
	if err != nil {
		t.Fatal(err)
	}
	if got := string(res.Vol()["/top/x.txt"]); got != "abab" {
		t.Fatalf("custom: %q", got)
	}
}

// A prop the bridge knows nothing about reaches its component, which is
// what lets the vocabulary need no entry per component.
func TestCmpTreePropsReachTheComponent(t *testing.T) {
	vol := treeGen(t, `{
	  "cmp":"File","props":{"name":"a.ts"},
	  "children":[
	    {"cmp":"Content","props":{"src":"class X {\n"}},
	    {"cmp":"Content","props":{"src":"y = 1\n","indent":2}},
	    {"cmp":"Content","props":{"src":"}\n"}}
	  ]
	}`)

	if got := string(vol["/top/a.ts"]); got != "class X {\n  y = 1\n}\n" {
		t.Fatalf("indent: %q", got)
	}
}
