/* Copyright (c) 2026 Richard Rodger, MIT License */

// THE CHECK GATE, END TO END (tools/cmptree-gen.js).
//
// `cmptree-gen --check <dir>` holds a committed tree to what the
// generators produce: generate into memory, compare with the tree on
// disk, exit non-zero on drift, and say which paths drifted and how.
//
// SPAWNED, not required. The contract a CI job depends on is the exit
// code and what lands on stderr, and neither is reachable by importing
// the module: a test that called an exported function would pass while
// the tool exited 0 on drift. The suite pays one process per case for
// that.
//
// A REAL FILESYSTEM, for the same reason. The tool's whole subject is
// the difference between generated bytes and committed bytes, so a
// memory volume on both sides would be testing the comparison against
// itself.

import { test, describe } from 'node:test'
import * as Assert from 'node:assert'
import * as Fs from 'node:fs'
import * as Os from 'node:os'
import * as Path from 'node:path'
import { spawnSync } from 'node:child_process'


const TOOL = Path.join(__dirname, '..', '..', 'tools', 'cmptree-gen.js')

const EXIT_OK = 0
const EXIT_DRIFT = 1
const EXIT_USAGE = 2


// One File node, its name the path relative to the output folder. The
// multi-segment form is the one rb-solar's nine generators produce --
// `app/models/planet.rb`, `db/migrate/...` -- and `validName` allows it,
// refusing only a `..` segment.
const file = (name: string, src: string) => ({
  cmp: 'File',
  props: { name },
  children: [{ cmp: 'Content', props: { src } }],
})


type Run = { code: number, out: string, err: string }

function tmp(): string {
  return Fs.mkdtempSync(Path.join(Os.tmpdir(), 'jostraca-cmptree-'))
}


function run(dir: string, tree: any, args: string[]): Run {
  const treefile = Path.join(dir, 'tree.json')
  Fs.writeFileSync(treefile, JSON.stringify(tree))
  const res = spawnSync(process.execPath, [TOOL, ...args, treefile], {
    encoding: 'utf8',
    // stdin closed: with no file argument the tool reads the tree from
    // it, and a case that lost the argument would otherwise hang the
    // whole suite rather than fail.
    stdio: ['ignore', 'pipe', 'pipe'],
  })
  return { code: res.status as number, out: res.stdout, err: res.stderr }
}


// The committed tree a check runs against, and the tree that produced
// it. `extra.txt` is on disk and in nobody's output: see
// `an-extra-file-on-disk-is-ignored`.
function seeded(): { dir: string, out: string, tree: any } {
  const dir = tmp()
  const out = Path.join(dir, 'app')
  Fs.mkdirSync(Path.join(out, 'models'), { recursive: true })
  Fs.mkdirSync(Path.join(out, 'config'), { recursive: true })
  Fs.writeFileSync(Path.join(out, 'models', 'planet.rb'),
    'class Planet\n  NAME = "earth"\nend\n')
  Fs.writeFileSync(Path.join(out, 'config', 'routes.rb'), 'root "planets"\n')
  Fs.writeFileSync(Path.join(out, 'extra.txt'), 'hand written\n')

  return {
    dir,
    out,
    tree: [
      file('models/planet.rb', 'class Planet\n  NAME = "earth"\nend\n'),
      file('config/routes.rb', 'root "planets"\n'),
    ],
  }
}


// Every file under `dir`, by path relative to it, so a case can state
// that a check changed nothing.
function listing(dir: string): string[] {
  const out: string[] = []
  const walk = (at: string, rel: string) => {
    for (const name of Fs.readdirSync(at).sort()) {
      const full = Path.join(at, name)
      const key = '' === rel ? name : rel + '/' + name
      if (Fs.statSync(full).isDirectory()) {
        walk(full, key)
      }
      else {
        out.push(key)
      }
    }
  }
  walk(dir, '')
  return out
}


describe('cmptree-gen', () => {

  // THE CLEAN CASE, and the shape rb-solar's generators produce: files
  // at nested paths, checked against a tree that already holds them.
  test('a-committed-tree-that-matches-is-clean', () => {
    const { dir, out, tree } = seeded()
    try {
      const res = run(dir, tree, ['--check', out])
      Assert.equal(res.code, EXIT_OK, res.err)
      Assert.match(res.out, /checked 2 file\(s\).*0 drifted/)
      Assert.equal(res.err, '')
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // A HAND EDIT IS DRIFT, and the report says which file and which
  // lines. `-` is what the tree holds and `+` is what the generators
  // produce, the way round every other diff a reviewer reads is
  // written.
  test('a-hand-edit-is-drift-and-is-named', () => {
    const { dir, out, tree } = seeded()
    try {
      Fs.writeFileSync(Path.join(out, 'models', 'planet.rb'),
        'class Planet\n  NAME = "EDITED"\nend\n')

      const res = run(dir, tree, ['--check', out])
      Assert.equal(res.code, EXIT_DRIFT)
      Assert.match(res.err, /models\/planet\.rb differs from the generated tree/)
      Assert.match(res.err, /line 2:/)
      Assert.match(res.err, /-\s*NAME = "EDITED"/)
      Assert.match(res.err, /\+\s*NAME = "earth"/)
      Assert.match(res.out, /1 drifted/)

      // The file the run did NOT touch is not mentioned.
      Assert.ok(!res.err.includes('routes.rb'), res.err)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // A FILE THE GENERATORS CLAIM AND THE TREE DOES NOT HOLD IS DRIFT.
  // The other direction from a hand edit, and the one a reviewer meets
  // when a generated file is deleted by accident.
  test('a-file-missing-from-the-tree-is-drift', () => {
    const { dir, out, tree } = seeded()
    try {
      Fs.rmSync(Path.join(out, 'config', 'routes.rb'))

      const res = run(dir, tree, ['--check', out])
      Assert.equal(res.code, EXIT_DRIFT)
      Assert.match(res.err, /config\/routes\.rb is missing from/)
      Assert.match(res.out, /1 drifted/)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // AN EXTRA FILE ON DISK IS IGNORED, and that is a decision rather
  // than an omission. rb-solar is why: nine generators write sixteen
  // files into a whole Rails application, so a check that called every
  // file it did not write "drift" would report the other eight
  // generators' output, and the hand-written tree around them, as a
  // failure. The cost is that a file which stops being generated
  // lingers unreported.
  test('an-extra-file-on-disk-is-ignored', () => {
    const { dir, out, tree } = seeded()
    try {
      Fs.writeFileSync(Path.join(out, 'models', 'unclaimed.rb'), 'gone\n')

      const res = run(dir, tree, ['--check', out])
      Assert.equal(res.code, EXIT_OK, res.err)
      Assert.match(res.out, /0 drifted/)
      Assert.ok(!res.err.includes('unclaimed'), res.err)
      Assert.ok(!res.err.includes('extra.txt'), res.err)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // A CHECK WRITES NOTHING, ANYWHERE -- including the run that reports
  // drift, and including jostraca's own meta folder. A command that
  // only asks a question must not be able to answer it by changing
  // something.
  test('a-check-writes-nothing', () => {
    const { dir, out, tree } = seeded()
    try {
      Fs.writeFileSync(Path.join(out, 'models', 'planet.rb'), 'drifted\n')
      const before = listing(out)

      const res = run(dir, tree, ['--check', out])
      Assert.equal(res.code, EXIT_DRIFT)

      Assert.deepEqual(listing(out), before,
        'a check left something behind: ' + listing(out).join(', '))
      Assert.equal(
        Fs.readFileSync(Path.join(out, 'models', 'planet.rb'), 'utf8'),
        'drifted\n', 'a check rewrote the file it was asked about')
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // RAW IS THIS TOOL'S DEFAULT, and is not the library default. The
  // input is final text somebody else evaluated, so a `$$...$$` in a
  // shell script, a makefile, a doc comment or a regex is bytes.
  // `--template` is the way back to rendering it.
  test('the-tool-hands-the-bytes-through-untouched', () => {
    const dir = tmp()
    const out = Path.join(dir, 'app')
    try {
      const src = 'sed -i "s/$$path$$/x/" f\necho $$"quoted"$$\n'
      Fs.mkdirSync(out, { recursive: true })
      Fs.writeFileSync(Path.join(out, 'a.sh'), src)

      const tree = [file('a.sh', src)]

      // Byte for byte, `$$` and all.
      const raw = run(dir, tree, ['--check', out])
      Assert.equal(raw.code, EXIT_OK, raw.err)

      // AND THE CONTROL: with rendering back on the same tree drifts,
      // because `$$"quoted"$$` renders its own literal with no model at
      // all. `model: {}` was the guard before `raw`, and this is the
      // case it does not cover.
      const templated = run(dir, tree, ['--template', '--check', out])
      Assert.equal(templated.code, EXIT_DRIFT)
      Assert.match(templated.err, /a\.sh differs/)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // --check ANSWERS A QUESTION; --folder PERFORMS A RUN. Letting one
  // silently win would make the exit code mean the other thing, which
  // is the failure a CI gate can least afford.
  test('usage-errors-exit-2', () => {
    const { dir, out, tree } = seeded()
    try {
      const both = run(dir, tree, ['--check', out, '--folder', dir])
      Assert.equal(both.code, EXIT_USAGE)
      Assert.match(both.err, /--check and --folder are alternatives/)

      const dry = run(dir, tree, ['--check', out, '--dryrun'])
      Assert.equal(dry.code, EXIT_USAGE)
      Assert.match(dry.err, /--check already writes nothing/)

      const nodir = run(dir, tree, ['--check', Path.join(dir, 'nope')])
      Assert.equal(nodir.code, EXIT_USAGE)
      Assert.match(nodir.err, /no such directory/)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // THE WRITE RUN STILL WRITES, and into the folder the operator named
  // rather than one the tree chose.
  test('the-write-run-still-writes', () => {
    const dir = tmp()
    try {
      const tree = [file('models/planet.rb', 'class Planet\nend\n')]
      const res = run(dir, tree, ['--folder', Path.join(dir, 'build')])
      Assert.equal(res.code, EXIT_OK, res.err)
      Assert.match(res.out, /^wrote .*models\/planet\.rb$/m)
      Assert.equal(
        Fs.readFileSync(
          Path.join(dir, 'build', 'models', 'planet.rb'), 'utf8'),
        'class Planet\nend\n')

      // ... and a dry run writes nothing while saying what it would.
      const dry = run(dir, tree, ['--folder', Path.join(dir, 'dry'), '--dryrun'])
      Assert.equal(dry.code, EXIT_OK, dry.err)
      Assert.match(dry.out, /^would write .*models\/planet\.rb$/m)
      Assert.equal(Fs.existsSync(Path.join(dir, 'dry', 'models')), false)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })


  // `--at` takes the tree from one key, because aontu prints the whole
  // document and the tree is usually one field of it.
  test('at-takes-one-key-of-the-document', () => {
    const { dir, out, tree } = seeded()
    try {
      const doc = { note: 'ignored', out: tree }
      const res = run(dir, doc, ['--at', 'out', '--check', out])
      Assert.equal(res.code, EXIT_OK, res.err)
      Assert.match(res.out, /0 drifted/)

      const missing = run(dir, doc, ['--at', 'nope', '--check', out])
      Assert.equal(missing.code, EXIT_USAGE)
      Assert.match(missing.err, /no value at key: nope/)
    }
    finally {
      Fs.rmSync(dir, { recursive: true, force: true })
    }
  })

})
