import { test, describe } from 'node:test'
import * as Assert from 'node:assert'

import { expect } from './expect'

import { memfs } from '../dist/util/memfs'

import {
  Jostraca,
  cmpTree,
  TREE_CMP,
  cmp,
} from '../'


// 2025-01-01T00:00:00.000Z
const START_TIME = 1735689600000

const clock = () => {
  let nowI = 0
  return () => START_TIME + (++nowI * (60 * 1000))
}


// Generate a component tree given as data, into an in-memory volume.
const gen = async (tree: any, opts?: any) => {
  const { fs, vol } = memfs({})
  const jostraca = Jostraca({ now: clock() })
  const info = await jostraca.generate(
    { fs: () => fs, folder: '/top' },
    cmpTree(tree, opts))
  return { info, vol: vol.toJSON() as any }
}


// THE BRIDGE (src/tree.ts, docs/design/AONTU.0.md). A component tree
// as plain data -- the shape aontu's Folder/File/Content primitives
// evaluate to -- generated by the same components a hand-written
// generator calls.
describe('tree', () => {

  // The worked example from the design note, verbatim: this is what
  // `aontu model.aon` prints for the aontu document there.
  test('aontu-tree-generates-files', async () => {
    const { info, vol } = await gen({
      cmp: 'Folder',
      props: { name: 'src' },
      children: [{
        cmp: 'File',
        props: { name: 'planet.ts' },
        children: [
          {
            cmp: 'Content',
            props: { src: 'export interface Planet {\n' },
            children: [],
          },
          { cmp: 'Content', props: { src: '  id: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '  name: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '  mass: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '}\n' }, children: [] },
        ],
      }],
    })

    expect(info.files.written).equal(['/top/src/planet.ts'])
    Assert.equal(vol['/top/src/planet.ts'],
      'export interface Planet {\n' +
      '  id: string\n' +
      '  name: string\n' +
      '  mass: string\n' +
      '}\n')
  })


  // A list root becomes siblings, which is what generate's synthetic
  // root node is for.
  test('sibling-roots', async () => {
    const { info } = await gen([
      {
        cmp: 'File', props: { name: 'a.txt' },
        children: [{ cmp: 'Content', props: { src: 'A' } }],
      },
      {
        cmp: 'File', props: { name: 'b.txt' },
        children: [{ cmp: 'Content', props: { src: 'B' } }],
      },
    ])
    expect(info.files.written).equal(['/top/a.txt', '/top/b.txt'])
  })


  // `props` and `children` are optional: a leaf with nothing to say is
  // a legitimate node.
  test('optional-props-and-children', async () => {
    const { info, vol } = await gen({
      cmp: 'Folder',
      props: { name: 'empty' },
    })
    expect(info.files.written).equal([])
    // The folder is still made.
    Assert.equal(vol['/top/empty'], null)
  })


  // NOTHING HERE IS LIMITED TO THE THREE PRIMITIVES aontu serves so
  // far: `cmp` names an exported component, so one this file has never
  // heard of works the moment it is exported.
  test('every-exported-component-is-reachable', async () => {
    Assert.deepEqual(Object.keys(TREE_CMP).sort(), [
      'Content', 'Copy', 'File', 'Folder', 'Fragment',
      'Inject', 'Line', 'List', 'Project', 'Slot',
    ])

    const { info, vol } = await gen({
      cmp: 'Project',
      props: { folder: 'sdk' },
      children: [{
        cmp: 'File',
        props: { name: 'x.txt' },
        children: [
          { cmp: 'Content', props: { src: 'a' } },
          { cmp: 'Line', props: { src: 'b' } },
        ],
      }],
    })

    expect(info.files.written).equal(['/top/sdk/x.txt'])
    Assert.equal(vol['/top/sdk/x.txt'], 'ab\n')
  })


  // A caller may add their own component, or override one.
  test('custom-components', async () => {
    const Twice = cmp(function Twice(props: any) {
      const node: any = props.ctx$.node
      node.kind = 'content'
      node.content = props.src + props.src
    })

    const { vol } = await gen({
      cmp: 'File',
      props: { name: 'x.txt' },
      children: [{ cmp: 'Twice', props: { src: 'ab' } }],
    }, { cmp: { Twice } })

    Assert.equal(vol['/top/x.txt'], 'abab')
  })


  // THE TREE IS THE CALLER'S DATA and must come back unchanged: `cmp()`
  // writes `ctx$` into the props object it is handed, so the bridge
  // passes a copy. Without it a tree parsed once and generated twice
  // carries the first run's context into the second.
  test('the-tree-is-not-scribbled-on', async () => {
    const tree = {
      cmp: 'File',
      props: { name: 'x.txt' },
      children: [{ cmp: 'Content', props: { src: 'a' } }],
    }
    const before = JSON.stringify(tree)

    await gen(tree)
    Assert.equal(JSON.stringify(tree), before)

    // ... and generating the same tree again is the same generation.
    const { vol } = await gen(tree)
    Assert.equal(vol['/top/x.txt'], 'a')
  })


  // A MALFORMED TREE IS REFUSED BY THE CALL THAT READS IT, before the
  // define phase has made a folder.
  test('malformed-trees-are-refused', () => {
    const bad = (tree: any) => {
      try {
        cmpTree(tree)
      }
      catch (err: any) {
        return err.message
      }
      return undefined
    }

    Assert.match(bad(null) as string, /node is not an object \(at \[0\]\)/)
    Assert.match(bad('File') as string, /node is not an object/)
    Assert.match(bad({}) as string, /node has no cmp name/)
    Assert.match(bad({ cmp: '' }) as string, /node has no cmp name/)
    Assert.match(bad({ cmp: 'Nope' }) as string, /unknown component: Nope/)
    Assert.match(bad({ cmp: 'File', props: [] }) as string,
      /props is not an object/)
    Assert.match(bad({ cmp: 'File', children: {} }) as string,
      /children is not an array/)

    // The path names the offending node.
    Assert.match(
      bad({ cmp: 'Folder', children: [{ cmp: 'File', children: [{}] }] }) as string,
      /node has no cmp name \(at \[0\]\/Folder\[0\]\/File\[0\]\)/)
  })

})
