import { test, describe } from 'node:test'
import * as Assert from 'node:assert'
import * as Fs from 'node:fs'
import * as Path from 'node:path'

import { expect } from './expect'

import { memfs } from '../dist/util/memfs'

import {
  Jostraca,
  cmpTree,
  TREE_CMP,
  cmp,
} from '../'
import { TREE_CMP_DEPRECATED, TREE_RAW_CMP } from '../dist/tree'


// 2025-01-01T00:00:00.000Z
const START_TIME = 1735689600000

const clock = () => {
  let nowI = 0
  return () => START_TIME + (++nowI * (60 * 1000))
}


// Generate a component tree given as data, into an in-memory volume.
// `seed` pre-populates that volume, for the components that READ a file.
const gen = async (tree: any, opts?: any, seed?: any) => {
  const { fs, vol } = memfs(seed || {})
  const jostraca = Jostraca({ now: clock() })
  const info = await jostraca.generate(
    { fs: () => fs, folder: '/top' },
    cmpTree(tree, opts))
  return { info, vol: vol.toJSON() as any }
}


// THE BRIDGE (src/tree.ts, docs/design/AONTU.0.md). A component tree
// as plain data -- the shape aontu's Folder/File/Content primitives
// evaluate to -- generated by the same components a hand-written
// generator calls.
describe('tree', () => {

  // The worked example from the design note, verbatim: this is what
  // `aontu model.aon` prints for the aontu document there.
  test('aontu-tree-generates-files', async () => {
    const { info, vol } = await gen({
      cmp: 'Folder',
      props: { name: 'src' },
      children: [{
        cmp: 'File',
        props: { name: 'planet.ts' },
        children: [
          {
            cmp: 'Content',
            props: { src: 'export interface Planet {\n' },
            children: [],
          },
          { cmp: 'Content', props: { src: '  id: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '  name: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '  mass: string\n' }, children: [] },
          { cmp: 'Content', props: { src: '}\n' }, children: [] },
        ],
      }],
    })

    expect(info.files.written).equal(['/top/src/planet.ts'])
    Assert.equal(vol['/top/src/planet.ts'],
      'export interface Planet {\n' +
      '  id: string\n' +
      '  name: string\n' +
      '  mass: string\n' +
      '}\n')
  })


  // A list root becomes siblings, which is what generate's synthetic
  // root node is for.
  test('sibling-roots', async () => {
    const { info } = await gen([
      {
        cmp: 'File', props: { name: 'a.txt' },
        children: [{ cmp: 'Content', props: { src: 'A' } }],
      },
      {
        cmp: 'File', props: { name: 'b.txt' },
        children: [{ cmp: 'Content', props: { src: 'B' } }],
      },
    ])
    expect(info.files.written).equal(['/top/a.txt', '/top/b.txt'])
  })


  // `props` and `children` are optional: a leaf with nothing to say is
  // a legitimate node.
  test('optional-props-and-children', async () => {
    const { info, vol } = await gen({
      cmp: 'Folder',
      props: { name: 'empty' },
    })
    expect(info.files.written).equal([])
    // The folder is still made.
    Assert.equal(vol['/top/empty'], null)
  })


  // NOTHING HERE IS LIMITED TO THE THREE PRIMITIVES aontu serves so
  // far: `cmp` names a registered component, so one this file has never
  // heard of works as soon as it has an entry.
  //
  // THE DRIFT GUARD is the second half of that claim, and it reads
  // `src/cmp/` rather than restating a list: a component file with no
  // entry in TREE_CMP is a component a data tree cannot reach, and
  // nothing else would say so. `None` is internal -- `generate` uses it
  // for the synthetic root node and no tree may name it.
  test('every-exported-component-is-reachable', async () => {
    const cmpdir = Path.join(__dirname, '..', 'src', 'cmp')
    const onDisk = Fs.readdirSync(cmpdir)
      .filter((f) => f.endsWith('.ts'))
      .map((f) => f.replace(/\.ts$/, ''))
      .filter((n) => 'None' !== n)
      .sort()
    Assert.deepEqual(Object.keys(TREE_CMP).sort(), onDisk,
      'src/cmp/ and TREE_CMP disagree: a component landed unreachable')

    const { info, vol } = await gen({
      cmp: 'Project',
      props: { folder: 'sdk' },
      children: [{
        cmp: 'File',
        props: { name: 'x.txt' },
        children: [
          { cmp: 'Content', props: { src: 'a' } },
          { cmp: 'Line', props: { src: 'b' } },
        ],
      }],
    })

    expect(info.files.written).equal(['/top/sdk/x.txt'])
    Assert.equal(vol['/top/sdk/x.txt'], 'ab\n')
  })


  // A PROP THE BRIDGE KNOWS NOTHING ABOUT reaches the component, which
  // is what makes the vocabulary need no entry per component. `indent`
  // is the one an aontu generator wants first: a span's own depth is
  // expressible without a new primitive.
  test('props-reach-the-component', async () => {
    const { vol } = await gen({
      cmp: 'File',
      props: { name: 'a.ts' },
      children: [
        { cmp: 'Content', props: { src: 'class X {\n' } },
        { cmp: 'Content', props: { src: 'y = 1\n', indent: 2 } },
        { cmp: 'Content', props: { src: '}\n' } },
      ],
    })
    Assert.equal(vol['/top/a.ts'], 'class X {\n  y = 1\n}\n')
  })


  // THE NAMES TWO COMPONENTS SHIPPED UNDER still resolve, so a tree
  // written against `Copy` or `List` keeps working.
  test('deprecated-names-still-resolve', async () => {
    Assert.deepEqual(Object.keys(TREE_CMP_DEPRECATED).sort(), ['Copy', 'List'])
    Assert.equal(TREE_CMP_DEPRECATED.Copy, TREE_CMP.CopyFiles)
    Assert.equal(TREE_CMP_DEPRECATED.List, TREE_CMP.ListItems)

    const { vol } = await gen({
      cmp: 'File',
      props: { name: 'l.txt' },
      children: [{
        cmp: 'List',
        props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'Content', props: { src: 'n={item.n}\n' } }],
      }],
    })
    Assert.equal(vol['/top/l.txt'], 'n=1\nn=2\n\n')
  })


  // RULE (3): THE BYTES IN A DATA TREE ARE ALREADY FINAL, usually.
  // `Content` and `Line` template what they are handed, so once a tree
  // is a generator's only output road EVERY byte it produces passes
  // through that render -- and a `$$` in a shell script, a makefile, a
  // doc comment or a regex is substituted from the generate model with
  // no diagnostic and exit 0.
  //
  // `raw` per node, `{raw: true}` for the whole tree, and the same tree
  // WITHOUT either as the control.
  test('raw-hands-the-bytes-through-untouched', async () => {
    const payload = [
      '#!/bin/sh',
      'sed -i "s/$$path$$/x/" f',
      'echo $$"quoted"$$',
      'echo $$__JOSTRACA_REPLACE__$$',
      "awk '{print $$1}'",
      'make: $$(VAR)$$',
    ].join('\n') + '\n'

    const tree = (props: any) => ({
      cmp: 'File',
      props: { name: 'a.sh' },
      children: [
        { cmp: 'Content', props: { src: payload, ...props } },
        { cmp: 'Line', props: { src: 'L $$path$$', ...props } },
      ],
    })

    const model = { path: 'ZZZ' }
    const run = async (t: any, opts?: any) => {
      const { fs, vol } = memfs({})
      await Jostraca({ now: clock() }).generate(
        { fs: () => fs, folder: '/top', model },
        cmpTree(t, opts))
      return (vol.toJSON() as any)['/top/a.sh']
    }

    const through = payload + 'L $$path$$\n'

    // The prop, per node ...
    Assert.equal(await run(tree({ raw: true })), through)

    // ... and the option, for every node in the tree.
    Assert.equal(await run(tree({}), { raw: true }), through)

    // THE CONTROL, unchanged: without either, three of those lines are
    // rewritten and two of the three do not need a model to be.
    const substituted = [
      '#!/bin/sh',
      'sed -i "s/ZZZ/x/" f',
      'echo quoted',
      'echo /(?<J_O>\\$\\$)(?<J_R>[^$]+)(?<J_C>\\$\\$)/',
      "awk '{print $$1}'",
      'make: $$(VAR)$$',
    ].join('\n') + '\nL ZZZ\n'

    Assert.equal(await run(tree({})), substituted)
    Assert.equal(await run(tree({ raw: false }), { raw: true }), substituted)
  })


  // THE OPTION IS A DEFAULT, NOT A STATEMENT, so it sits beneath both
  // of the more specific ones: a node's own props, and the bindings a
  // parent makes for this invocation. `ListItems` is where the second
  // one bites -- its `{item.n}` macro is a `replace` entry, so a child
  // rendered raw emits the macro verbatim, and that is the cost of the
  // whole-tree option rather than a defect in it.
  test('raw-is-outranked-by-the-node-and-by-the-parent', async () => {
    const listtree = (props: any) => ({
      cmp: 'File',
      props: { name: 'l.txt' },
      children: [{
        cmp: 'ListItems',
        props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'Content', props: { src: 'n={item.n}\n', ...props } }],
      }],
    })

    const run = async (t: any, opts?: any) => {
      const { fs, vol } = memfs({})
      await Jostraca({ now: clock() }).generate(
        { fs: () => fs, folder: '/top' }, cmpTree(t, opts))
      return (vol.toJSON() as any)['/top/l.txt']
    }

    // Under a whole-tree `raw`, the macro is bytes like any other.
    Assert.equal(await run(listtree({}), { raw: true }), 'n={item.n}\nn={item.n}\n\n')

    // The node outranks the option ...
    Assert.equal(await run(listtree({ raw: false }), { raw: true }), 'n=1\nn=2\n\n')

    // ... and with no option at all nothing changed.
    Assert.equal(await run(listtree({})), 'n=1\nn=2\n\n')
  })


  // THE WHOLE-TREE OPTION MUST BE SAFE ON A WHOLE TREE, and it was not.
  // `Fragment` and `CopyFiles` validate a CLOSED prop set, so setting
  // `raw` on every node -- the first spelling of the option -- made
  // either component refuse the run outright: "the property raw is not
  // allowed". A whole-tree option that cannot be used on a tree holding
  // two of the ten components is not a whole-tree option.
  //
  // So the option reaches TREE_RAW_CMP, and this generates every
  // registered component under it: a component that would refuse `raw`
  // fails here rather than in a consumer's pipeline.
  test('raw-option-is-safe-on-every-component', async () => {
    Assert.deepEqual(TREE_RAW_CMP, [TREE_CMP.Content, TREE_CMP.Line],
      'TREE_RAW_CMP is the components that render text they were handed')

    const from = '/frag.txt'
    const seed = {
      [from]: 'HEADER\n<[SLOT]>\nFOOTER\n',
      '/src/copied.txt': 'COPIED\n',
      '/top/inject.txt': 'A\n#--START--#\n\n#--END--#\nB\n',
    }

    // One node per component, each in a place its op accepts.
    const tree = [
      {
        cmp: 'Project', props: { folder: 'sdk' },
        children: [{
          cmp: 'Folder', props: { name: 'f' },
          children: [{
            cmp: 'File', props: { name: 'x.txt' },
            children: [
              { cmp: 'Content', props: { src: 'c' } },
              { cmp: 'Line', props: { src: 'l' } },
              {
                cmp: 'Fragment', props: { from },
                children: [{ cmp: 'Slot', props: { name: 's' } }],
              },
              {
                cmp: 'ListItems', props: { item: [{ n: 1 }] },
                children: [{ cmp: 'Content', props: { src: 'i' } }],
              },
              { cmp: 'CopyFiles', props: { from: '/src/copied.txt', to: 'c.txt' } },
            ],
          }],
        }],
      },
      // A sibling of the Project, so it edits a file at the output root:
      // a Project's folder does not outlive its subtree (#26).
      {
        cmp: 'Inject', props: { name: 'inject.txt' },
        children: [{ cmp: 'Content', props: { src: 'INJECTED\n' } }],
      },
    ]

    // Every component of the registry is exercised above; a new one
    // landing unreachable is the drift guard's business, and a new one
    // landing REFUSING the option is this test's.
    Assert.deepEqual(
      Object.keys(TREE_CMP).sort(),
      ['Content', 'CopyFiles', 'File', 'Folder', 'Fragment', 'Inject',
        'Line', 'ListItems', 'Project', 'Slot'],
      'a component joined the registry: give it a node above')

    const { vol } = await gen(tree, { raw: true }, seed)

    // The run completed, and `raw` reached the two that render text.
    Assert.equal(vol['/top/sdk/f/x.txt'],
      'cl\nHEADER\n\nFOOTER\ni\nCOPIED\n')
    Assert.equal(vol['/top/inject.txt'],
      'A\n#--START--#\nINJECTED\n\n#--END--#\nB\n')
  })


  // A caller may add their own component, or override one.
  test('custom-components', async () => {
    const Twice = cmp(function Twice(props: any) {
      const node: any = props.ctx$.node
      node.kind = 'content'
      node.content = props.src + props.src
    })

    const { vol } = await gen({
      cmp: 'File',
      props: { name: 'x.txt' },
      children: [{ cmp: 'Twice', props: { src: 'ab' } }],
    }, { cmp: { Twice } })

    Assert.equal(vol['/top/x.txt'], 'abab')
  })


  // THE TREE IS THE CALLER'S DATA and must come back unchanged: `cmp()`
  // writes `ctx$` into the props object it is handed, so the bridge
  // passes a copy. Without it a tree parsed once and generated twice
  // carries the first run's context into the second.
  test('the-tree-is-not-scribbled-on', async () => {
    const tree = {
      cmp: 'File',
      props: { name: 'x.txt' },
      children: [{ cmp: 'Content', props: { src: 'a' } }],
    }
    const before = JSON.stringify(tree)

    await gen(tree)
    Assert.equal(JSON.stringify(tree), before)

    // ... and generating the same tree again is the same generation.
    const { vol } = await gen(tree)
    Assert.equal(vol['/top/x.txt'], 'a')
  })


  // TWO FILES AT ONE PATH IS REFUSED. `aontu render` refuses an
  // absolute path, a `..` segment and a DUPLICATE over its unit list;
  // the first two were already here (`validFolder` above, and
  // `validName` for a File or Folder name) and the third was the gap.
  // After the retirement there is no other holder for it.
  //
  // The guard is at the BUILD PHASE rather than in `cmpTree`, where
  // this was asked for, because that is where the path is final: a
  // `File` name composes with whatever `Project` and `Folder` nesting
  // encloses it, so deciding it from the tree would mean a second
  // implementation of path composition -- the one thing `cmpTree` is
  // built not to have. One implementation, every road in.
  test('two-files-at-one-path-are-refused', async () => {
    const refused = async (tree: any) => {
      try {
        await gen(tree)
      }
      catch (err: any) {
        return err.message
      }
      return undefined
    }

    // The plain case: two siblings, one name.
    Assert.match(
      await refused([
        { cmp: 'File', props: { name: 'a.txt' } },
        { cmp: 'File', props: { name: 'a.txt' } },
      ]) as string,
      /two File components resolve to the same output path, path=\/top\/a\.txt/)

    // COMPOSED PATHS, which is what makes this the build phase's
    // business: two different statements of nesting arriving at one
    // file. Neither node's own name is a duplicate of the other's.
    Assert.match(
      await refused([
        {
          cmp: 'Folder', props: { name: 'x' },
          children: [{ cmp: 'File', props: { name: 'a.txt' } }],
        },
        { cmp: 'File', props: { name: 'x/a.txt' } },
      ]) as string,
      /path=\/top\/x\/a\.txt/)

    // The message names BOTH nodes, because "a duplicate" is useless
    // without the pair.
    Assert.match(
      await refused([
        { cmp: 'Folder', props: { name: 'x' }, children: [{ cmp: 'File', props: { name: 'a.txt' } }] },
        { cmp: 'Folder', props: { name: 'x' }, children: [{ cmp: 'File', props: { name: 'a.txt' } }] },
      ]) as string,
      /first=x\/a\.txt, second=x\/a\.txt/)

    // A FILE UNDER `ListItems` is the case a static check over the tree
    // could never see: one node, two invocations, one path.
    //
    // AND IN A DATA TREE IT IS ALWAYS THAT. A `File` name is NOT
    // templated -- `File` assigns `props.name` to the node and `FileOp`
    // composes it as given -- so `f{item.n}.txt` is a filename
    // containing braces, not two filenames. A hand-written generator
    // varies the name by computing it in the host language, which a
    // data child has no way to do; a document that wants N files states
    // N `File` nodes. See `list-items-cannot-vary-a-file-name`.
    Assert.match(
      await refused({
        cmp: 'ListItems',
        props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'File', props: { name: 'same.txt' } }],
      }) as string,
      /path=\/top\/same\.txt/)
  })


  // The half of the rule above that is about `File` rather than about
  // duplicates: a data tree cannot interpolate a file name, so the
  // macro is refused as the duplicate it is rather than silently
  // writing one file called `f{item.n}.txt`.
  test('list-items-cannot-vary-a-file-name', async () => {
    let msg = ''
    try {
      await gen({
        cmp: 'ListItems',
        props: { item: [{ n: 1 }, { n: 2 }], line: false },
        children: [{ cmp: 'File', props: { name: 'f{item.n}.txt' } }],
      })
    }
    catch (err: any) {
      msg = err.message
    }
    Assert.match(msg, /path=\/top\/f\{item\.n\}\.txt/)

    // One `File` node per file is the form that works.
    const { info } = await gen([
      { cmp: 'File', props: { name: 'f1.txt' } },
      { cmp: 'File', props: { name: 'f2.txt' } },
    ])
    expect(info.files.written).equal(['/top/f1.txt', '/top/f2.txt'])
  })


  // A MALFORMED TREE IS REFUSED BY THE CALL THAT READS IT, before the
  // define phase has made a folder.
  test('malformed-trees-are-refused', () => {
    const bad = (tree: any) => {
      try {
        cmpTree(tree)
      }
      catch (err: any) {
        return err.message
      }
      return undefined
    }

    Assert.match(bad(null) as string, /node is not an object \(at \[0\]\)/)
    Assert.match(bad('File') as string, /node is not an object/)
    Assert.match(bad({}) as string, /node has no cmp name/)
    Assert.match(bad({ cmp: '' }) as string, /node has no cmp name/)
    Assert.match(bad({ cmp: 'Nope' }) as string, /unknown component: Nope/)
    Assert.match(bad({ cmp: 'File', props: [] }) as string,
      /props is not an object/)
    Assert.match(bad({ cmp: 'File', children: {} }) as string,
      /children is not an array/)

    // The path names the offending node.
    Assert.match(
      bad({ cmp: 'Folder', children: [{ cmp: 'File', children: [{}] }] }) as string,
      /node has no cmp name \(at \[0\]\/Folder\[0\]\/File\[0\]\)/)

    // A NAME INHERITED FROM Object.prototype IS NOT A COMPONENT.
    // `cmps['toString']` answers on any ordinary object, and the call
    // then ran `Object.prototype.toString` as a component: no node, no
    // output, and no error to say so.
    Assert.match(bad({ cmp: 'toString' }) as string,
      /unknown component: toString/)
    Assert.match(bad({ cmp: 'constructor' }) as string,
      /unknown component: constructor/)
  })


  // THE TREE MAY NOT CHOOSE THE OUTPUT ROOT. `ProjectOp` takes `folder`
  // as given -- an absolute path unchanged, a relative one joined to the
  // base -- which is right when a developer wrote the call and wrong
  // when the tree arrived as JSON: `cmptree-gen --folder ./build` would
  // otherwise write wherever the input said. `File` and `Folder` names
  // are already refused a `..` segment by `validName`; `folder` had no
  // such check because nothing could reach it from data.
  test('a-tree-cannot-escape-the-output-folder', async () => {
    const bad = (folder: any) => {
      try {
        cmpTree({ cmp: 'Project', props: { folder } })
      }
      catch (err: any) {
        return err.message
      }
      return undefined
    }

    Assert.match(bad('/escaped') as string, /folder must not be absolute/)
    Assert.match(bad('../../escaped') as string,
      /folder must not contain a "\.\." segment/)
    Assert.match(bad('a/../../b') as string,
      /folder must not contain a "\.\." segment/)
    Assert.match(bad(1) as string, /folder is not a string/)

    // A folder BELOW the root is what the prop is for, and still works.
    const { info } = await gen({
      cmp: 'Project',
      props: { folder: 'sdk' },
      children: [{
        cmp: 'File', props: { name: 'x.txt' },
        children: [{ cmp: 'Content', props: { src: 'a' } }],
      }],
    })
    expect(info.files.written).equal(['/top/sdk/x.txt'])
  })


  // THE PARENT'S ARGUMENTS REACH THE CHILD. `List` walks its children
  // once per item with `{item, indent, replace}`, and the `{item.n}`
  // macro means nothing without them -- a hand-written child takes them
  // as its parameter, and a data child has no parameter list, so the
  // thunk merges them under the node's own props.
  test('list-items-reach-their-children', async () => {
    const { vol } = await gen({
      cmp: 'File',
      props: { name: 'l.txt' },
      children: [{
        cmp: 'ListItems',
        props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'Content', props: { src: 'n={item.n}\n' } }],
      }],
    })
    Assert.equal(vol['/top/l.txt'], 'n=1\nn=2\n\n')
  })


  // A PARENT'S BINDINGS REACH THE CHILD; A PARENT'S OWN PROPS DO NOT.
  // `Project` passes `args: props` -- the very object it was handed --
  // so its `name` and `folder` arrived in every direct child's props.
  // For eight components that is invisible; for the two that validate a
  // CLOSED prop set it was fatal, and `project([copyfiles(...)])` was
  // refused with `the properties "name, folder" are not allowed`.
  //
  // Only the DATA path could reach it: a hand-written child is an arrow
  // that ignores its parameter and writes its own props. THE GO PORT
  // WAS ALREADY RIGHT -- its `Project` builder passes a nil inherit map
  // -- so this is the `Line` case again, and the fix went into
  // TypeScript.
  test('a-parents-own-props-do-not-reach-a-data-child', async () => {
    const seed = { '/src/a.txt': 'A\n', '/src/f.txt': 'F\n' }

    // The two with a closed prop set, directly under a Project.
    const copied = await gen({
      cmp: 'Project', props: { name: 'p', folder: 'sdk' },
      children: [{ cmp: 'CopyFiles', props: { from: '/src/a.txt', to: 'a.txt' } }],
    }, undefined, seed)
    Assert.equal(copied.vol['/top/sdk/a.txt'], 'A\n')

    const fragmented = await gen({
      cmp: 'Project', props: { name: 'p', folder: 'sdk' },
      children: [{
        cmp: 'File', props: { name: 'f.txt' },
        children: [{ cmp: 'Fragment', props: { from: '/src/f.txt' } }],
      }],
    }, undefined, seed)
    Assert.equal(fragmented.vol['/top/sdk/f.txt'], 'F\n')

    // AND THE ONE THAT IS NOT A PARENT'S PROPS still arrives:
    // `ListItems` binds `{item, indent, replace}` for each invocation,
    // which is what makes `{item.n}` mean anything.
    const listed = await gen({
      cmp: 'File', props: { name: 'l.txt' },
      children: [{
        cmp: 'ListItems', props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'Content', props: { src: 'n={item.n}\n' } }],
      }],
    })
    Assert.equal(listed.vol['/top/l.txt'], 'n=1\nn=2\n\n')

    // A `Content` under a `Project` no longer takes the project's name
    // as its own, which is the same fix seen from the other end.
    const named = await gen({
      cmp: 'Project', props: { name: 'p', folder: 'sdk' },
      children: [{
        cmp: 'File', props: { name: 'c.txt' },
        children: [{ cmp: 'Content', props: { src: 'C' } }],
      }],
    })
    expect(named.info.files.written).equal(['/top/sdk/c.txt'])
  })


  // A CLOSED PROP SET HAS TO ADMIT THE ENGINE'S OWN BINDINGS.
  // `ListItems` binds `item`, `indent` and `replace` for each
  // invocation of its children, and a data child -- having no parameter
  // list to take them as -- receives all three merged under its own
  // props. `Fragment` and `CopyFiles` validate a CLOSED set, met an
  // `item` they had never heard of, and refused: a Fragment repeated
  // once per entity is an ordinary generator and it could not be
  // written as a tree at all. THE GO PORT WAS ALREADY RIGHT -- its
  // props are a struct, so an unknown key in the map is never looked at.
  test('a-closed-prop-set-admits-the-engines-bindings', async () => {
    const seed = { '/src/a.txt': 'A\n', '/src/f.txt': 'F {item.n}\n' }

    // A fragment per item, with the macro resolving from the binding.
    const fragmented = await gen({
      cmp: 'File', props: { name: 'x.txt' },
      children: [{
        cmp: 'ListItems', props: { item: [{ n: 1 }, { n: 2 }] },
        children: [{ cmp: 'Fragment', props: { from: '/src/f.txt' } }],
      }],
    }, undefined, seed)
    Assert.equal(fragmented.vol['/top/x.txt'], 'F 1\nF 2\n\n')

    // And a copy per item, which reaches the same merge.
    const copied = await gen({
      cmp: 'File', props: { name: 'y.txt' },
      children: [{
        cmp: 'ListItems', props: { item: [{ n: 1 }] },
        children: [{
          cmp: 'CopyFiles', props: { from: '/src/a.txt', to: 'a.txt' },
        }],
      }],
    }, undefined, seed)
    Assert.equal(copied.vol['/top/a.txt'], 'A\n')

    // The refusal it must NOT have cost: a prop neither the component
    // nor the engine names is still refused, which is the whole value
    // of a closed set.
    let msg = ''
    try {
      await gen({
        cmp: 'File', props: { name: 'z.txt' },
        children: [{ cmp: 'Fragment', props: { from: '/src/f.txt', nosuchprop: 1 } }],
      }, undefined, seed)
    }
    catch (err: any) {
      msg = err.message
    }
    Assert.match(msg, /nosuchprop/)
  })


  // THE COPY IS DEEP ENOUGH THAT NO COMPONENT CAN REACH THE TREE. A
  // spread of the outer props was not: `Fragment` writes its slot
  // markers into `props.replace`, so a tree carrying one came back with
  // extra keys, accumulated them on a second generate, and threw
  // outright if the map was frozen.
  test('nested-props-are-not-scribbled-on', async () => {
    const from = '/frag.txt'
    const seed = { [from]: 'HEADER\n<[SLOT]>\nFOOTER\n' }

    const replace: Record<string, any> = {}
    const tree = {
      cmp: 'File',
      props: { name: 'f.txt' },
      children: [{
        cmp: 'Fragment',
        props: { from, replace },
        children: [{ cmp: 'Content', props: { src: 'BODY\n' } }],
      }],
    }

    const first = await gen(tree, undefined, seed)
    Assert.equal(first.vol['/top/f.txt'], 'HEADER\nBODY\n\nFOOTER\n')

    // The caller's own map is untouched ...
    Assert.deepEqual(Object.keys(replace), [])

    // ... so a frozen one generates rather than throwing, and the same
    // tree generates the same bytes a second time.
    Object.freeze(replace)
    const second = await gen(tree, undefined, seed)
    Assert.equal(second.vol['/top/f.txt'], 'HEADER\nBODY\n\nFOOTER\n')
  })

})
